### ISSUE TITLE
platform-tools upgrade version 29.06.6

### ISSUE THREAD

**Issue by axi92** [Genymobile/scrcpy#1206]
I have the issue that we install the platform-tools from the sdkmanager for android.
Although there is no new release note on the website 
A new version is out for platform-tools: Version 29.0.6-6198805
With a new adb version:
```
Android Debug Bridge version 1.0.41
Version 29.0.6-6198805
Installed as /opt/android/platform-tools/adb
```

The main problem ist that the adb version is not the same as in scrcpy.

**Comment by rom1v** [comment]
> The main problem ist that the adb version is not the same as in scrcpy.

The protocol is 1.0.41, like the version shipped with scrcpy. What's the concrete issue?

I upgrade platform-tools on every release. If you want to use another `adb`, just set the environment variable `export ADB=/path/to/your/adb` before running scrcpy.

**Comment by axi92** [comment]
I get the message when I do `adb connect IP:port` and then `scrcpy`:
```
INFO: scrcpy 1.12 <https://github.com/Genymobile/scrcpy>
adb server version (41) doesn't match this client (39); killing...
* daemon started successfully
adb: error: failed to get feature set: no devices/emulators found
ERROR: "adb push" returned with value 1
```

And with the env var:
```
INFO: scrcpy 1.12 <https://github.com/Genymobile/scrcpy>
exec: No such file or directory
ERROR: Command not found: [/opt/android/platform-tools/adb], [push], [/usr/local/share/scrcpy/scrcpy-server], [/data/local/tmp/scrcpy-server.jar]
ERROR: (make 'adb' accessible from your PATH or define its fullpath in the ADB environment variable)
ERROR: Could not execute "adb push"
```

**Comment by rom1v** [comment]
Oh, I guess you use the snap package, then. I think it packages adb 39, and since it runs from a sandboxed environment and cannot access your `/opt/android/platform-tools/adb`.

I think that it can access `/home`, so if you put your `adb` somewhere in your home, it should work: https://github.com/Genymobile/scrcpy/issues/527#issuecomment-550786305

Alternatively, you could use `scrcpy.adb` for your others commands.

Alternatively, you could use the "normal" version (not the snap package, `adb install scrcpy` on Ubuntu 20.04 (not released yet) or Debian testing/sid, or build it :/)

**Comment by axi92** [comment]
I am on ubuntu 18.04.
I don't like snap that much because of this issue =)
I tried to set a symlink but that does not work but when I copy the adb binary to my home it works. 
Thank you for your help!
