### ISSUE TITLE
FRP Lock issue

### ISSUE THREAD

**Issue by akwaaa** [Genymobile/scrcpy#1220]
So, i have a Samsung Galaxy J5 2017 (J530F) and i use scrcpy daily on it. Yesterday, i turned off my phone via scrcpy (ctrl + P and then i pressed turn off WITH scrcpy), and when i restarted my phone, it was FRP locked. (Don't worry, i know how to flash the stock ROM to disable FRP lock) My phone is rooted but i'm on the official stock ROM (no TWRP or anything) since 1-2 months. If someone knows how to fix this?

**Comment by rom1v** [comment]
Hmm, never hears about that.

Are you sure it's related to scrcpy?

**Comment by akwa-dev** [comment]
Not sure, but my phone was factory resetted so i don't know what could've caused that.
I don't have this phone rn (at my grandma's house, and i can't go there because of the coronavirus, smh xd) but when i'll have it i can test this one more time to see if it's related.
Thanks for the fast response!

**Comment by akwa-dev** [comment]
(J'viens juste de voir que t'es français, j'peux te parler plus facilement du coup :D)
