### ISSUE TITLE
No camera rotation with "Ctrl+r"

### ISSUE THREAD

**Issue by frenksisco** [Genymobile/scrcpy#1232]
Hi, first of all thank you very much for this wonderful free tool. I know other people have this problem but I haven't understood if there is a fix. When my official Motorola camera app is in landascape mode, scrcpy screen remains in portrait mode. It doesn't rotate even if I do "Ctrl + r"
Is there any way to fix it? Thanks

**Comment by rom1v** [comment]
It cannot rotate with `Ctrl`+`r` because it's a portrait-only app.

The camera apps often never rotate the screen, but only its components (to avoid a reinitialization of the camera on rotation).

See #218.

On current development branch (`dev`), a new option has been added (by #1151) to force the mirroring orientation. You can build it if you want to test. It will be available in the next release.
