### ISSUE TITLE
Question about touch events

### ISSUE THREAD

**Issue by ironyman** [Genymobile/scrcpy#1247]
Hi! This isn't really an issue. I'm trying to make a macro automation app and I noticed you're using this thing to inject touch events

```
    private boolean injectEvent(InputEvent event) {
        return device.injectInputEvent(event, InputManager.INJECT_INPUT_EVENT_MODE_ASYNC);
    }
```

Can you use this in any old android app or what are the requirements for this?

Thanks!

**Comment by rom1v** [comment]
You need the "system" permission `android.permission.INJECT_EVENT`:

https://github.com/aosp-mirror/platform_frameworks_base/blob/07f7d30449bf2e0009aca4c034f4b48517af1ecc/core/res/AndroidManifest.xml#L3069-L3076

Shell has this permission:

https://github.com/aosp-mirror/platform_frameworks_base/blob/07f7d30449bf2e0009aca4c034f4b48517af1ecc/packages/Shell/AndroidManifest.xml#L78

That's why a Java program executed via `adb shell` can inject events.

**Comment by ironyman** [comment]
Thanks much!
