### ISSUE TITLE
Lack of input on --display 2/DeX mode

### ISSUE THREAD

**Issue by lovintoja** [Genymobile/scrcpy#1288]
- OS: Windows
 - scrcpy version: 1.12.1
 - installation method: Windows release
 - device model: S8+
 - Android version: 9.0

So, I've just downloaded latest stable release, paste'd scrcpy and scrcpy-server from dev branch (as posted in another issue), and wanted to test it with my DeX, so basically hook my S8+ to the docking station and share input of my notebook to the desktop mode of my phone. Dumpsys shows 3 displays: 0 - internal, 2 - desktop mode (DeX), 10 - marked as HDMI output (shown only when hooked to docking station, has mHasContent=false).

Choosing --display 0 without any problems. When I write --display 2 and try to give any input, I get "CANNOT ASSOCIATE A DISPLAY ID TO THE INPUT EVENT". --display 10 shows nothing, as expected. 

<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/63618924/79168345-92122e00-7de1-11ea-9bdd-d8daac8c0e6b.png">

**Comment by rom1v** [comment]
Réf: https://github.com/Genymobile/scrcpy/pull/1177#issuecomment-591333921

@peanutwolf Since the `setDisplayId()` method is not available before Android 10:

https://github.com/Genymobile/scrcpy/blob/eb8f7a1f288b43e333db12e0f329e7706da5a164/server/src/main/java/com/genymobile/scrcpy/wrappers/InputManager.java#L50-L60

I think that `supportsInputEvents()` should just just return `Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q` (whatever the presentation flag):

https://github.com/Genymobile/scrcpy/blob/eb8f7a1f288b43e333db12e0f329e7706da5a164/server/src/main/java/com/genymobile/scrcpy/Device.java#L118-L123

What do you think?

Also, when not supported, I'm not sure we should disable "power mode":

https://github.com/Genymobile/scrcpy/blob/eb8f7a1f288b43e333db12e0f329e7706da5a164/server/src/main/java/com/genymobile/scrcpy/Controller.java#L115-L119

**Comment by peanutwolf** [comment]
@rom1v if `supportsInputEvents()` will return only `Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q` when on device with API lower then 29 and displays that has FLAG_PRESENTATION touch events will be forwarded on wrong display.
AOSP doc clearly states that input events can't be forwarded on external displays until API 29.

My guess that we should attempt to call `setDisplayId` only on SDK >= Q


@lovintoja 
> share input of my notebook to the desktop mode of my phone

 I couldn't clearly understand how it works. Without scrcpy you connect some kind of touch screen to DeX?

**Comment by rom1v** [comment]
@peanutwolf Something like 0e272561d6397c8e1159005845cf80dba6c8f2c4?

**Comment by peanutwolf** [comment]
> @peanutwolf What about something like [0e27256](https://github.com/Genymobile/scrcpy/commit/0e272561d6397c8e1159005845cf80dba6c8f2c4)?

Yes, correct

**Comment by rom1v** [comment]
> Android version: 9.0

OK, so to summarize: input events on secondary displays may not work before Android 10.

However, they were not disabled explicitly in your case, this is fixed by 94a7f1a0f84cb4bc998e7eb117517209e3ca5584.
