### ISSUE TITLE
Add controls to move the image for large screens that overflow the window

### ISSUE THREAD

**Issue by viktor1190** [Genymobile/scrcpy#141]
There is a way to "pan" the window when I'm in pixel perfect size mode? because the mobile screen is cut off by the monitor so I only can see a little portion of the large mobile screen's.
If not, this would be a nice feature to inspect pixel-perfect easily, like pressing down Ctrl while move the mouse to look around.

**Comment by rom1v** [comment]
> There is a way to "pan" the window when I'm in pixel perfect size mode?

No, there isn't.

> If not, this would be a nice feature to inspect pixel-perfect easily, like pressing down Ctrl while move the mouse to look around.

IMO, this is the job of your window manager.

On XFCE, Alt+Click-and-move from anywhere in the Window moves it. IIRC, Gnome and KDE have similar shortcuts. What's your OS/desktop environment?

**Comment by viktor1190** [comment]
I'm using Ubuntu 16.04.1, I didn't knew that feature about the windows manager.
However I belive this shouldn't depend of the window manager, would be nice to have a global shorcut for that and what about Windows or OSX?. But it's only my personal opinion you're the expert my friend.

PD: Do you know that shortcut for the ubuntu window manager?

**Comment by rom1v** [comment]
> However I belive this shouldn't depend of the window manager, would be nice to have a global shorcut for that and what about Windows or OSX?

Controlling how to move the window is still the job of the window manager. If it does not support it, I understand that it may be tempting to implement it in the application, but it's a safe way to add a lot of bugs for one or another wm :)

A "pan" feature (without resizing the window) might be possible, but I can't think of a way to make it simple and intuitive, and IMO it adds too much complexity (i.e. more bugs) compared to the benefits.

> Do you know that shortcut for the ubuntu window manager?

It seems to be Alt+click ([source](https://help.ubuntu.com/community/KeyboardShortcuts). Otherwise, test Super+click or Ctrl+Alt+click.
