### ISSUE TITLE
screen off but keep mirroring option (ctrl+o) uses as much battery as screen on

### ISSUE THREAD

**Issue by j-chan-9108** [Genymobile/scrcpy#1460]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: windows 10
 - scrcpy version: 1.14
 - installation method: windows release
 - device model: xiaomi mi mix 2s
 - Android version: 10

**Describe the bug**
- the battery usage with the screen off but keep mirroring option (ctrl+o) uses as much battery as screen on. when i use the ctrl+p option to turn off the screen though, the battery usage is normal as if the screen is off (but then the problem is i cant see the screen anymore on scrcpy). is this supposed to happen?

**Comment by rom1v** [comment]
It's probably device-dependent.

It's expected that it consumes more battery than when the device is off (where there is no "running app"). The screen should not consume battery though (if it's really off and not backlighted), so it should consume a bit less.

Anyway, I'm closing, since scrcpy just requests the device to turn its screen off. How it impacts the battery is out of the control of scrcpy.
