### ISSUE TITLE
Turn the screen on if the connection with scrcpy is dropped abruptly

### ISSUE THREAD

**Issue by brunoais** [Genymobile/scrcpy#1572]
**Is your feature request related to a problem? Please describe.**
Sometimes I disconnect my phone from the PC and the screen is left off.
I may forget that the phone is actually not locked and not even asleep and I leave the phone like that possibly for too long.
Also, my wifi is not very stable and I'm enough of a security freak but I also love the convenience so I care to press the "OK" every time I connect to the phone in debug mode.

By adding this behavior, I can control my phone immediately when a disconnect happens without having to press power twice (or 3 times, if the phone is already asleep):

In sum, reduce these steps:
1. Wake up (but screen doesn't) (Only if asleep)
2. Sleep + lock
3. Wake up; screen wake up
4. Fill in the pattern
5. (confirm fingerprint) Press OK

To:
1. (confirm fingerprint)  Press OK

Extra:
I intent to implement this myself. It can also allow me to familiarize with these workings of android.
This issue is to confirm if I have green light for such feature in scrcpy

**Comment by rom1v** [comment]
Hi,

> Sometimes I disconnect my phone from the PC and the screen is left off.
> I may forget that the phone is actually not locked and not even asleep and I leave the phone like that possibly for too long.

> This issue is to confirm if I have green light for such feature in scrcpy

Yes, I already encounter this problem :wink: Thank you for tackling this.

The code to modify is in [`CleanUp.java`](https://github.com/Genymobile/scrcpy/blob/master/server/src/main/java/com/genymobile/scrcpy/CleanUp.java) (see 2f74ec2518377103e144684a9fb0c2d358168bbb).

Since we can't know if the current power mode is NORMAL or OFF, I suggest to always set it to NORMAL on close.
Therefore, the clean up process must always be started (currently, `CleanUp.configure()` starts it only if there were things to clean up), and the `main` method must call `Device.setScreenPowerMode()`.

(Don't forget to start from the `dev` branch.)

**Comment by rom1v** [comment]
#1576 30714aba34e8b447159beaebeaf4eeab7bd33907
