### ISSUE TITLE
Should be able to set defaul MOD key and able to use both ctrls

### ISSUE THREAD

**Issue by aeroxy** [Genymobile/scrcpy#1792]
Older scrcpy versions use ctrl and command on macOS for MOD and I am able to use both ctrls but now the default is command which is in conflict with macOS' default hide shortcut (android HOME). We should be able to set defaul MOD key and able to use both ctrls.

**Comment by rom1v** [comment]
The default is either <kbd>Alt</kbd> or <kbd>Cmd</kbd>. The reason is that <kbd>Ctrl</kbd> is now forwarded to the device (to trigger Android shortcuts directly (see #1598).

You can change the shortcut mod: https://github.com/Genymobile/scrcpy#shortcuts
You can set <kbd>Ctrl</kbd> if you want (but then you won't be able to forward <kbd>Ctrl</kbd>+<kbd>key</kbd> to the device).
