### ISSUE TITLE
Lagging on Redmi Note 3 pro (Wireless mode)

### ISSUE THREAD

**Issue by Genxster1998** [Genymobile/scrcpy#1795]
Same as #699 
 it works fine with adb reverse enabled on my Redmi Note 7 pro (sd675) on Q(10.0) ,ping~10-100ms
But on Redmi Note 3 pro Marshmallow (sd650),it's falling back always to adb forward (failed reverse mode) and having pathetic fps ...
using as both client or server **ap**  as well as **p2p** where ping around 1-5ms. 

Is it android version issue ?

**Comment by rom1v** [comment]
> it works fine with adb reverse enabled on my Redmi Note 7 pro

The fact that it works correctly wirelessly depends mainly on two things:
 - the device ROM (whether it handles wireless with good performances)
 - the wireless connection

For example, since I have a new Wifi 5GHz connection, I can mirror my OnePlus 7 Pro at 8Mbps (or more) at 1440x3120 without any problem. With my old connection, I could not.
But with my new connection, another device (Samsung Galaxy A3) does not work well correctly if the bitrate is above 2Mbps.

> Same as #699

Then please don't open a new issue, just answer on this one. I'm closing as duplicate.
