### ISSUE TITLE
KeyMapping tool

### ISSUE THREAD

**Issue by OUCHAIB** [Genymobile/scrcpy#1807]
is there a key mapping to be able to play some games using mouse/keyboard of the pc,
is there a way to increase texture resolution ? thank you

**Comment by rom1v** [comment]
> is there a key mapping to be able to play some games using mouse/keyboard of the pc

#712

> is there a way to increase texture resolution ?

By default, it use a texture having the size of your device.

**Comment by OUCHAIB** [comment]
the texture are not the same between mobile and scrcpy
<img width="266" alt="andriod" src="https://user-images.githubusercontent.com/66299056/95015971-f05cf280-0647-11eb-9ef1-ea19391ef45c.png">
![androidtoo 1](https://user-images.githubusercontent.com/66299056/95016174-28186a00-0649-11eb-9ef8-2d755a265e11.png)

**Comment by rom1v** [comment]
Because your desktop screen is smaller than your device, the texture has the same size, but is drawn on a smaller area. Press <kbd>Alt</kbd>+<kbd>g</kbd> to resize your window "pixel-perfect" to see the difference.

What is the texture size printed in the console output when you start scrcpy? What is your computer screen resolution?

**Comment by OUCHAIB** [comment]
here what I have in the console : 
[server] INFO: Device: Sony G8141 (Android 9)
INFO: Renderer: direct3d
INFO: Initial texture: 1080x1920

my laptop's display  resolution is 1080x1920 too, my android has 3840 x 2160 display

**Comment by rom1v** [comment]
> my laptop's display resolution is 1080x1920 too

But your device is portrait. On your first screenshot, the area of the device is 525×933, while the device is 1080×1920 (so it's about 4× smaller).

If you put your device in landscape and switch to fullscreen (<kbd>Alt</kbd>+<kbd>f</kbd>), you'll get the exact same definition and the quality will be good.

> my android has 3840 x 2160 display

It seems to be 1080×1920. What's the result of `adb shell wm size`? But anyway, a greater Android device display size would make the problem even worse.

Rendering to a big target size (on the device), capturing the screen and draw it on a smaller area is inherently lossy. What makes the problem worse is that the downscaling is linear if you don't use OpenGL (read [highlights of v1.13 §"Downscaling quality (trilinear filtering)"](https://github.com/Genymobile/scrcpy/releases/tag/v1.13) for more details).

To enable trilinear filtering on Windows, you must switch to OpenGL: `scrcpy --render-driver=opengl`.
Unfortunately, on Windows, the OpenGL drivers are often less performant or totally buggy. If that works for you, great. Otherwise, you need either a bigger screen or try on Linux.

**Comment by OUCHAIB** [comment]
Thanks for that man , I was wondering why other softwars (Apowermirror for example ) aren't have the issue , do they use different methode to mirror throw usb ?,

And what about Keymapping is that exists?

**Comment by rom1v** [comment]
> I was wondering why other softwars (Apowermirror for example ) aren't have the same issue

They probably write their shaders in DirectX directly (instead of OpenGL) for their Windows-specific app.

> And what about Keymapping is that exists?

No, see #712.
