### ISSUE TITLE
somehow it only shows a blackscreen if i try to cast my oculus quest to sidequest

### ISSUE THREAD

**Issue by keksblatt** [Genymobile/scrcpy#1991]
hey i was trying to set up a streaming setup to stream some vr games but somehow scrcpy only shows a blackscreen. can someone tell me whats going on there? i have the latest version of sidequest and scrcpy.

**Comment by TheDrHax** [comment]
This issue is somehow related to the Guardian system. Casting works only if:

1) Safety boundary is not visible;
2) You are not in passthrough mode (double tap on the side of headset);
3) You don't use passthrough home environment;

I tried to downgrade firmware to the old UI, but I think it is not possible anymore. The only reliable fix is to completely disable Guardian system or to move boundary far away enough to not trigger it during casting.

**Comment by keksblatt** [comment]
thank you alot. now it works now perfectly fine ^^

**Comment by Utopiah** [comment]
Can confirm and point 1 is tricky because you "assume" that's fine since it does display something, but it's not. Even a small part of the guardian goes straight to black. I assume that most of us do some tests and recording sitting in front of the computer, at least to start and thus at the edge of the guardian. That just doesn't work. I ended up disabling it entirely. It's a shame because I thought demo-ing the guardian itself to go in and out of VR was very pedagogical for newcomers but... yep, not possible anymore. 

Thanks for clarifying.

**Comment by Tirarex** [comment]
OVRMetricsTool will break streaming, i dsabled overlay and streaming now works fine.

**Comment by carloslogg** [comment]
how many billions they spent developing this garbage?  so hard to get a real time stream without tricks and workarounds.

**Comment by rom1v** [comment]
Related to #5913?
