### ISSUE TITLE
Minor: adb.exe process continues to run after scrcpy is closed

### ISSUE THREAD

**Issue by HatTrkPatrk** [Genymobile/scrcpy#205]
Very minor issue on Win10 (other Windows OSes unconfirmed as I don't have access to them to test) in the grand scheme of things but felt it should be logged anyway.

After closing scrcpy, the adb.exe process it launches continues to run in the background, requiring termination via the Task Manager.

I'm unsure what (if any) information would be helpful in diagnosing this, or even if anything can be done about it (seeing as the exe is an Android one not technically scrcpy) but I can provide any needed details.

**Comment by rom1v** [comment]
This is expected. `adb` starts a daemon as soon as you use it, which is used for every `adb` command.

Even without _scrcpy_, just type `adb devices` for example, the daemon will stay started.

Killing it would be wrong, since it would break any other parallel usage of `adb` when you close _scrcpy_.

**Comment by mruac** [comment]
If you had to reference this issue many times @rom1v , why not add the command to the main main release so that this is done automatically?

**Comment by rom1v** [comment]
Implemented option `--kill-adb-on-close`: a3cdf1a6b86ea22786e1f7d09b9c202feabc6949
