### ISSUE TITLE
Low quality scrcpy -b 2M

### ISSUE THREAD

**Issue by rupamking1** [Genymobile/scrcpy#2131]
I use  scrcpy -b 2M commend but  still Low-quality screen

**Comment by rom1v** [comment]
```
scrcpy -b20m
```

Screenshot?

**Comment by rupamking1** [comment]
I used scrcpy --bit-rate 8M --max-size 10000 but still same problem

**Comment by rom1v** [comment]
Screenshot, please.

**Comment by rupamking1** [comment]
<img width="217" alt="Screenshot_1" src="https://user-images.githubusercontent.com/57300218/108506115-520fb780-72de-11eb-8e9c-1b52d5307241.png">

**Comment by rom1v** [comment]
OK, then it's #40: the resolution of your device is far bigger than the one from your computer.

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#the-quality-is-low

Press <kbd>Alt</kbd>+<kbd>g</kbd> in scrcpy to mirror "pixel perfect" (so it should be very big).

I have some pending work to support better scaling algorithms, but it will not be perfect: you need a better computer screen to mirror a high-definition device screen.

**Comment by rupamking1** [comment]
my screen is full hd and phone screen is also full hd

**Comment by rom1v** [comment]
> phone screen is also full hd

What is the output in the console (`New texture: …`) when you run scrcpy?

> my computer screen is full hd

On the screenshots, your device is mirrored in a 431×936 window (because it's in portrait mode). Even if your device is full hd (1080p), it means that 1080 pixels have to be downscaled to 431 pixels, so the mirroring downscales more than 4 times (twice in each direction).

You should try in landscape mode and fullscreen (or maximized).

This does not mean there is no problem, as I said scrcpy needs better downscalers (I have pending work on it). The goal was just to explain the problem.
