### ISSUE TITLE
Anyway to manually rotate scrcpy view on PC without changing orientation on phone ?

### ISSUE THREAD

**Issue by jayachar88** [Genymobile/scrcpy#218]
From this other issue report (https://github.com/Genymobile/scrcpy/issues/2), I learnt that some Camera apps don't reinitialize (and thus scrcpy I presume doesn't detect orientation change), when shooting in landscape mode (when phone was initially in portrait orientation). 

**Is there some possibility to manually force only the view on PC to rotate (to landscape orientation), without impacting the device orientation ?** 

This will allow scrcpy view for camera (default camera app on stock Android) to show correct orientation. If camera app is closed and another app is started, I believe scrcpy can detect the right orientation to display, over-riding the previous manual view (not device) orientation change.

**Comment by vctls** [comment]
I used the desktop orientation as a workaround. It's not exactly practical, especially since it seems there aren't any keyboard shortcut to do that on my PC, but hey, it works.

**Comment by diyism** [comment]
Upvote this feature request.

For example, we can add "--output-orientation" or abbr "--oo" to scrcpy command:
scrcpy --oo  0         //default orientation
scrcpy --oo  1         //rotate 90 degrees
scrcpy --oo  2         //rotate 180 degrees
scrcpy --oo  3         //rotate 270 degrees

**Comment by dre-z17** [comment]
> 
> 
> I used the desktop orientation as a workaround. It's not exactly practical, especially since it seems there aren't any keyboard shortcut to do that on my PC, but hey, it works.

Thank you for the idea. Since I use dual monitors your idea is a fast workable workaround for the meantime for recording and seeing landscaped videos properly as they are recording.

Another option for me when I need to record landscaped videos is to use Open Camera. The image is displayed correctly on screen but unfortunately records in portrait mode, regardless of phone orientation. But post-recording editing flips the videos back into landscape layout.  Is an extra step but better than not being able to see recorded landscaped videos in proper layout while recording if all a person has is a single monitor.

Scrcpy has not run into rotation issues on my phone in any other type of app so far. Only camera apps. Looking forward  to this forced rotation of the PC window without affecting the cellphone itself.

**Comment by Stamoulohta** [comment]
Created a pull request #1151 for the orientation (client) feature.

Cheers :)

**Comment by rom1v** [comment]
A new option `--lock-video-orientation` has been implemented on `dev` branch, by #1151. :tada:

**Comment by rom1v** [comment]
Please review #1274, which adds `Ctrl`+`←` and `Ctrl`+`→` shortcuts to rotate the scrcpy window.

**Comment by rom1v** [comment]
Released in v1.13.

**Comment by diyism** [comment]
```
wget https://github.com/Genymobile/scrcpy/archive/v1.13.tar.gz
wget https://github.com/Genymobile/scrcpy/releases/download/v1.13/scrcpy-server-v1.13
tar -xzpf v1.13.tar.gz
cd v1.13.tar.gz
meson x --buildtype release --strip -Db_lto=true -Dprebuilt_server=./scrcpy-server-v1.13
ninja -Cx
sudo ninja -Cx install
adb connect 192.168.0.122:5555   #my cellphone ip
scrcpy
ctrl+→
```

The screen orientation on my computer is OK now.

Great thanks to  @Stamoulohta  for this client-only rotation feature.

**Comment by rom1v** [comment]
> The screen orientation on my computer is OK now.

@diyism Glad that your problem is solved :)

> Great thanks to @Stamoulohta for this client-only rotation feature.

@Stamoulohta did a great work on mirroring orientation (#1151 `--lock-video-orientation`, that you could use instead if you want to record your game in the correct orientation), but I did the client-only rotation feature (#1274 `--rotation`, Ctrl+← and Ctrl+→) :wink:

**Comment by diyism** [comment]
Haha,  thank you for your fantastic work! @rom1v

**Comment by shehzadaliqadri** [comment]
Upvote this Feature Request, for version scrcpy 1.24 (07.01.2023)

if you wish to rotate the scrcpy output screen on PC,
for example, we can add "--lock-video-orientation=1" command:

--lock-video-orientation=0 //default orientation
--lock-video-orientation=1 //rotate 90 degrees
--lock-video-orientation=2 //rotate 180 degrees
--lock-video-orientation=3 //rotate 270 degrees

`--lock-video-orientation=1`
for most of the users

**Comment by perrette** [comment]
If it a desktop setting I'm not aware of, or was it updated to `ALT + LEFT` and `ALT + RIGHT` ? (scrcpy 2.3.1 ; Ubuntu 22.04)

**Comment by rom1v** [comment]
@perrette Yes, the default shortcuts modifier has been changed a long time ago (since v1.15 by https://github.com/Genymobile/scrcpy/pull/1598).

https://github.com/Genymobile/scrcpy/blob/master/doc/shortcuts.md
