### ISSUE TITLE
Screen waking when app closes

### ISSUE THREAD

**Issue by N1NJ4** [Genymobile/scrcpy#2216]
windows
1.17 release
P545 Android 9

Upon closing the application with screen off and stay awake on, after a few minutes or so the screen turns on.

Unsure if its a fixable problem or just how android handles a situation of those options changing in some specified way, no more stay awake and it turns the screen on, only for it to end up sleeping because it couldn't without polling the screen to turn off...

**Comment by rom1v** [comment]
There are two separate states:
 - the physical device screen
 - the Android display

With `--turn-screen-off`, it only turn off the device screen (the content is still visible in scrcpy).
When you close scrcpy, it turn it on (and since the Android display was on, it is still on).

A new option has been added in `dev` branch: see #824.

**Comment by N1NJ4** [comment]
Yup, that's the same, my mistake. Thanks,
