### ISSUE TITLE
memory leak when run with --v4l2_sink=

### ISSUE THREAD

**Issue by cadadr** [Genymobile/scrcpy#2279]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Debian Buster
 - scrcpy version: dev branch, commit 41a0383
 - installation method: manual build
 - device model: HTC Desire 728G Dual Sim
 - Android version: 5.1

**Describe the bug**

I built and ran scrcpy as such:

    ADB=/home/g/Android/Sdk/platform-tools/adb ./run x --v4l2_sink=/dev/video0

It worked as expected but the memory usage began to increase rapidly, consuming all of 16GB of available memory eventually.

It increases way faster when a camera app is open on the phone (tried both stock app and OpenCamera, the same).

When I do the same without v4l2-loopback integration,

     ADB=/home/g/Android/Sdk/platform-tools/adb ./run x

the memory increase does __not__ happen, scrcpy consumes suprisingly low memory actually.

**Comment by rom1v** [comment]
This is the kind of bug report which is very useful to detect problems introduced on the `dev` branch, thank you very much! :+1:

The memory leak is fixed by 1cde68a1fa01a9b37eeede3310edf163d4e79970.
An additional (small) memory leak on error is fixed by 84f17fdeab518cbe9f9c1a5fdf7dc50981c01806.

> `--v4l2_sink`

Oops, it seems I failed something in my rebase. Renamed to `--v4l2-sink` by 45e72801484deae6c931a4a79595b606227e547a.

**Comment by cadadr** [comment]
You're very welcome and thank you sooo much!! I had a zoom meeting for tomorrow, this is literally godsend :smile_cat: 

Tested standalone and with an OBS v4l2 connection and both memory usage and CPU usage are stable (maybe somewhat noticably higher than without v4l2 tho, at 18.8% CPU at 3.6/9GHz and 7.2%mem w/ 16GB mem, I can test and report back on Thursday if that's unexpected).
