### ISSUE TITLE
Screen not showing properly on portrait

### ISSUE THREAD

**Issue by The-ThirtyFour** [Genymobile/scrcpy#2435]
**Environment**
 - OS: Windows 10 Pro
 - scrcpy version: 1.18
 - installation method: Windows Release
 - device model: Samsung Galaxy Tab E (SM-T113NU)
 - Android version: LineageOS 14.1

The screen is glitched, like if it is sliced on stretched diagonal bars. And, when i try to click, it says that the touch event was ignored cuz it was generated for a "different device size". But in landscape it displays properly and i can click.

portrait:
```
INFO: Renderer: direct3d
INFO: Initial texture: 600x1024
INFO: New texture: 608x1024
[server] WARN: Ignore touch event, it was generated for a different device size
[server] WARN: Ignore touch event, it was generated for a different device size
```
landscape:
```
INFO: New texture: 1024x600
```

![image](https://user-images.githubusercontent.com/72163582/123844071-f935d880-d8e8-11eb-83ef-9d74c2196462.png)

![image](https://user-images.githubusercontent.com/72163582/123844481-782b1100-d8e9-11eb-854f-261388b9153e.png)

**Comment by rom1v** [comment]
Scrcpy request to encode the device screen at its native size 600x1024, and the encoder produces a frame at a different size:
```
INFO: Initial texture: 600x1024
INFO: New texture: 608x1024
```

The device encoder seems to expect a number of rows multiple of 16 (whereas the device size is not even a multiple of 16). 

You could probably reduce the size a bit so that the height is 592x1008 (`scrcpy -m 1008`).

Or maybe try another encoder: https://github.com/Genymobile/scrcpy#encoder

**Comment by The-ThirtyFour** [comment]
the ```scrcpy -m 1008``` worked, thank you!
