### ISSUE TITLE
Can I customize the buffer size?

### ISSUE THREAD

**Issue by kenken890922** [Genymobile/scrcpy#248]
How to customize the buffer size in decoder(or renderer), I know this will increase the latency(lag), but I want to stabilize the render time between two frames, I think maybe a larger buffer could stabilize the rendertime.
It will be better if buffer size is one of the options.
Thanks.🙂

**Comment by rom1v** [comment]
> How to customize the buffer size in decoder(or renderer)

There is no explicit buffer here. The socket buffer is [copied](https://github.com/Genymobile/scrcpy/blob/v1.3/app/src/decoder.c#L19) directly into the FFmpeg buffers to decode the video.

> I want to stabilize the render time between two frames

You mean, a constant framerate?

This is not possible, on the device, a new video frame is generated on every surface change, which has no reason to happen at a constant rate.

**Comment by rom1v** [comment]
That's true, and having no buffering was deliberate (to minimize lag). There is no timestamp on the device-side, so the frames are decoded displayed as soon as they are available.

In practice (at least over USB), jitter is very low.

To preserve delay between frames, they would have to be timestamped on the device and buffered on the client. To make it compatible with existing software, I think the server could expose the screen content as an RTSP stream (but then, it would just do mirroring, without mouse or key events, but since there would be more lag, events would probably not be so useful). But for that purpose (i.e. without events), it would be better to use a _real_ Android application (i.e. not over adb) using the projection API, so that adb would not be needed.
