### ISSUE TITLE
How time .deb package?

### ISSUE THREAD

**Issue by systmrrr** [Genymobile/scrcpy#256]
It is difficult to install on linux. Will the debian package come out?

**Comment by rom1v** [comment]
This would not be one `.deb`, but one per distrib+version+arch. Even if we limit to adm64, this would typically mean to create/maintain 2 or 3 versions for Debian + 2 or 3 versions for Ubuntu...

I would prefer it to be packaged by the distribution.

Someone recently [opened an RFS](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907295) so that its package would be uploaded to the Debian official repositories. That would be awesome. But no answer for now.

**Comment by johnsie** [comment]
Hi, I have a deb on my site and the Ubuntu Forums:

https://xn--joh-9ma.com/control-your-android-device-in-ubuntu-with-scrcpy/
https://ubuntuforums.org/showthread.php?t=2401019

I'm interested in making tweaks and improving the deb, so please help with feedback. I'm also interested in contacting anyone who has successfully managed to do the compile on Ubuntu or Debian.

**Comment by systmrrr** [comment]
thank you
i will feedback

**Comment by johnsie** [comment]
Link works ok for me

**Comment by tgmasterx1987** [comment]
to download the deb file you need to try it with https my friend ....

**Comment by johnsie** [comment]
Thanks for the heads-up. Apologies. That's a personal server and I was changing the HDD and doing some OS/Software updates on it. Should be back now. If anyone wants to mirror it feel free.

**Comment by adbaditya** [comment]
> Thanks for the heads-up. Apologies. That's a personal server and I was changing the HDD and doing some OS/Software updates on it. Should be back now. If anyone wants to mirror it feel free.

@johnsie hey the link is down. Got an error 403 FORBIDDEN.
Any other links available?

**Comment by johnsie** [comment]
htts://johñ.com/files/scrcpy_1.3~git20180820-2.2_amd64.deb

Sent from Yahoo Mail on Android 
 
  On Mon, 10 Dec 2018 at 11:53, Aditya Bajaj<notifications@github.com> wrote:   

Thanks for the heads-up. Apologies. That's a personal server and I was changing the HDD and doing some OS/Software updates on it. Should be back now. If anyone wants to mirror it feel free.


@johnsie hey the link is down. Got an error 403 FORBIDDEN.
Any other links available?

**Comment by camlafit** [comment]
Hello 

I've just tried on my debian 9.6
I got this error 
`scrcpy: error while loading shared libraries: libavformat.so.58: cannot open shared object file: No such file or directory
`
libavformat-dev is installed

**Comment by johnsie** [comment]
apt-get install libavdevice58 libavfilter6

**Comment by camlafit** [comment]
Hello
I've tried to install these version, but I've got some conflict version with libavcodec58, libavfilter7, libavformat58, libsdl2-2.0-0

**Comment by AWalton** [comment]
Hopefully we'll get an AppImage (my preferred option), Snap or Flatpak package instead of a DEB or RPM. That way it'll mean @rom1v only has to support one method of installation on Linux but everyone can still use it.

**Comment by camlafit** [comment]
Hello

Will be nice to have a flatpak or any other standalone binary but has not same purpose than a deb/rpm/... provided by any other package system.

In case should be a great progress :) at least to try it

**Comment by sisco311** [comment]
Just created a snap: https://github.com/sisco311/scrcpy-snap
It's in the snap store. Next week I will try to focus on the documentation.

**Comment by rom1v** [comment]
@sisco311 Thank you :+1:

**Comment by jimmyferiawan** [comment]
@johnsie how able to compile the source code in debian 9.9 ? i get stuck when installing dependencies  
ibegl1-mesa-dev : Depends: libegl1-mesa (= 13.0.6-1+b2) but 18.2.8-2~bpo9+1 is to be installed
                    Depends: libwayland-egl1-mesa (= 13.0.6-1+b2)
                    Depends: libdrm-dev (>= 2.4.69) but it is not going to be installed
                    Depends: libxcb-dri3-dev but it is not going to be installed
                    Depends: libwayland-dev (>= 1.2.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by DanielRios549** [comment]
I create a package for Ubuntu 18.04, if you guys want to test this excellent program without effect the boot time of your system, here it is. https://mega.nz/#!HMlH1IyB!B0Xtx9HrUlrefzlcjp7MZDy-lYPoVfzsWDKZSxU-U5o

**Comment by el-guahiro** [comment]
Good instructions for compiling the program from the link
https://4pda.ru/forum/index.php?showtopic=915423

**Comment by AzureRaptor** [comment]
> I can maybe look at getting a ppa or something set up when I get some free time as I think just having a deb is probably not the best way of going about this, even in the short term.

So, it's been over a year.  What's the status on getting a PPA for this package?  Getting it into the distro repos will take forever, and even if it is, it'll always be way out of date.  A PPA would be much more preferable.

**Comment by bananenfisch** [comment]
Rolling distributions like Debian "sid" or "testing" are normally up-to-date, when a package gets a maintainer (and Ubuntu are based on testing). Looks like, scrcpy is just blocked, because it depends on the old JDK 8 (and not on latest JDK):
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=893279

**Comment by el-guahiro** [comment]
Good dayIf you install all the dependencies and deb package from here  https://mega.nz/#!HMlH1IyB!B0Xtx9HrUlrefzlcjp7MZDy-lYPoVfzsWDKZSxU-U5oor  from here https://yadi.sk/d/Ez8ykhFOjh-qyg  then everything works fine in Xubuntu 18.04.Probably, this deb package can be installed in the latest versions of Debian, you only need to roll back to JDK 8.I can't check, since I have Xubuntu 18.04 on all  devices.With best regardsAndrew Shirokov , el guahirohttps://forum.xubuntu-ru.net/index.php?board=9.0  27.10.2019, 19:28, "bananenfisch" <notifications@github.com>:Rolling distributions like Debian "sid" or "testing" are normally up-to-date, when a package gets a maintainer (and Ubuntu are based on testing). Looks like, scrcpy is just blocked, because it depends on the old JDK 8 (and not on latest JDK):https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=893279—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rom1v** [comment]
> Looks like, scrcpy is just blocked, because it depends on the old JDK v8 (and not on latest JDK):
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=893279

Thank you for the link. The last comment says:

> blocked since upstream is unwilling to support JDK 9

I'm willing to support newer jdk, it's just that it seems the Android build system does not support it (see #3 #524).

If anyone have a solution for this, I would be happy to fix it.

**Comment by el-guahiro** [comment]
Maybe you should make an appimage? Andew    27.10.2019, 21:27, "Romain Vimont" <notifications@github.com>:Looks like, scrcpy is just blocked, because it depends on the old JDK v8 (and not on latest JDK):https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=893279Thank you for the link. The last comment says:blocked since upstream is unwilling to support JDK 9I'm willing to support newer jdk, it's just that it seems the Android build system does not support it (see #3 #524).If anyone have a solution for this, I would be happy to fix it.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rom1v** [comment]
> > blocked since upstream is unwilling to support JDK 9
>
> I'm willing to support newer jdk, it's just that it seems the Android build system does not support it (see #3 #524).

In fact, it seems to work now. I just tested with java 11 (java 9 is not packaged in Debian sid anymore).

**Comment by bananenfisch** [comment]
> In fact, it seems to work now. I just tested with java 11 (java 9 is not packaged in Debian sid anymore).

:-) thats good news - should i post it on debian tracker? may be, they are willing to maintain now...

**Comment by rom1v** [comment]
A new [RFS](https://wiki.debian.org/DebianMentorsFaq#How_do_I_get_a_sponsor_for_my_package.3F) have been submitted by Yangfl: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=944334

**Comment by rom1v** [comment]
https://packages.debian.org/sid/scrcpy 🎉 

Big thanks to Yangfl :+1:

**Comment by el-guahiro** [comment]
Hi 👍Happy new year! el guahiro   27.12.2019, 14:15, "Romain Vimont" <notifications@github.com>:https://packages.debian.org/sid/scrcpy 🎉Big thanks to Yangfl 👍—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rzr** [comment]
https://tracker.debian.org/pkg/scrcpy

 A new upstream version is available: 1.13 high
