### ISSUE TITLE
After mingw64 is successfully built, why does the server path point to other locations?

### ISSUE THREAD

**Issue by Helaer** [Genymobile/scrcpy#2585]
After mingw64 is successfully built, why does the server path not point to the local path?

Compile command:
1.meson x --buildtype release --strip -Db_lto=true -Dprebuilt_server=server/scrcpy-server
2.ninja.exe -Cx

![scrcpy 01](https://user-images.githubusercontent.com/52807664/130629686-091eb5f2-ea51-48bc-92a4-00d2d8a40954.png)
![scrcpy 0](https://user-images.githubusercontent.com/52807664/130629703-76c519ab-2667-47d0-a63a-45dc58e48d4b.png)
![scrcpy 2](https://user-images.githubusercontent.com/52807664/130629732-bf65b761-fe59-4e34-a4ee-35a193069f5e.png)

**Comment by rom1v** [comment]
(Please post terminal output as text instead of screenshots)

By default, it "installs" (and searches) in the "prefix dir" (`/usr` or `/usr/local` on Linux, resulting in `/usr/share/scrcpy/scrcpy-server`).

If you want that `scrcpy` searches `scrcpy-server` in its own directory, you must enable `-Dportable=true` in your meson command:
https://github.com/Genymobile/scrcpy/blob/d6aaa5bf9aa3710660c683b6e3e0ed971ee44af5/meson_options.txt#L5

This is what the Windows release script does:

https://github.com/Genymobile/scrcpy/blob/d6aaa5bf9aa3710660c683b6e3e0ed971ee44af5/release.mk#L88

**Comment by Helaer** [comment]
> -Dportable=true

It's done. Thank you very much!

> （请将终端输出作为文本而不是屏幕截图发布）
> 
> 默认情况下，它在“前缀目录”中“安装”（并搜索）（`/usr`或`/usr/local`在 Linux 上，导致`/usr/share/scrcpy/scrcpy-server`）。
> 
> 如果你想在它自己的目录中`scrcpy`搜索`scrcpy-server`，你必须`-Dportable=true`在你的介子命令中启用：
> https://github.com/Genymobile/scrcpy/blob/d6aaa5bf9aa3710660c683b6e3e0ed971ee44af5/meson_options.txt#L5
> 
> 这是 Windows 发布脚本的作用：
> 
> https://github.com/Genymobile/scrcpy/blob/d6aaa5bf9aa3710660c683b6e3e0ed971ee44af5/release.mk#L88

It's done. Thank you very much!
