### ISSUE TITLE
i,b frame interval

### ISSUE THREAD

**Issue by pranshuthegamer** [Genymobile/scrcpy#2642]
**Describe the solution you'd like**
the ability to choose frame interval, not fps but settings for things like b frames and i frames.
that way, we can choose whenever a full image is sent

**Comment by rom1v** [comment]
It possible to pass arbitrary [`MediaFormat`](https://developer.android.com/reference/android/media/MediaFormat) options using `--codec-options`.

For example, [`KEY_I_FRAME_INTERVAL`](https://developer.android.com/reference/android/media/MediaFormat#KEY_I_FRAME_INTERVAL)

```bash
scrcpy --codec-options i-frame-interval=5
# since Android 7, i-frame-interval accepts floats
scrcpy --codec-options i-frame-interval:float=5.5
```

Note that B-frames are better disabled for real-time, since referencing a further frame requires to delay the frames.

**Comment by pranshuthegamer** [comment]
ty
