### ISSUE TITLE
Please let adb be on all the time 

### ISSUE THREAD

**Issue by AsamurGH** [Genymobile/scrcpy#2754]
Hello,
I'm a disabled person who isn't able to physically use the mobile. This app is something truly amazing and now I got to finally use it in a different way, thank you! I use the wi-fi connection to not harm the phone's battery. But problem is that everytime I restart or sleep my laptop, I have to ask someone to plug the phone again to enable adb over TCP/IP. That is really bothersome, Is it possible to make the adb on just once, so I wouldn't have to plug the mobile few times a day?

**Comment by rom1v** [comment]
Unfortunately, without rooting the device, it is not possible to keep adb listening on TCP/IP on reboot.

It is possible to enable it without plugging on USB:
 - in Developer options, some devices allow to enable `Wireless ADB debugging`
 - since Android 11, there is a [pairing mechanism](https://developer.android.com/studio/command-line/adb#connect-to-a-device-over-wi-fi-android-11+)

However, that probably won't help you. :/

> I use the wi-fi connection to not harm the phone's battery

I think that leaving recent devices always plugged in should not damage the battery. I'm not an expert though.

**Comment by AsamurGH** [comment]
Oh, that's a bummer :/ The app is working like a charm, but I really need something on wi-fi and trustworthy. Thank you for reply!

**Comment by akano12** [comment]
> Oh, that's a bummer :/ The app is working like a charm, but I really need something on wi-fi and trustworthy. Thank you for reply!

there are plenty of tutorials on how to root your device,
in case you want to root your device,i suggest you use this app (google play link)[https://play.google.com/store/apps/details?id=com.sujanpoudel.adbwifi] to keep adb active all the time

**Comment by vintotal** [comment]
If you are able to root your device, you can put a script in the startup of Magisk (I call it activer_adbwifi.sh).
`!/data/adb/service.d
sleep 30
setprop service.adb.tcp.port 5555
stop adbd
[activer_adbwifi.txt](https://github.com/Genymobile/scrcpy/files/7533836/activer_adbwifi.txt)

start adbd`

**Comment by ahmedragab202** [comment]
hello , iknow its a bit late , but ive setup my phone with auto debugging , auto adb detection and auto scrcpy on ubuntu , i can do the same on winfows i hope , if you still need i can help you
