### ISSUE TITLE
No-Console Batch file code to run with other commands.  --no-console?

### ISSUE THREAD

**Issue by JASHIKO** [Genymobile/scrcpy#2830]
Hello, 
sorry if this has been asked a million times, but is it possible to create a batch file that opens SCRCPY without the console window? I have a batch file that does what I want now, however, I would like it to open scrcpy without the console window. Is this possible at all? And if so what command would i need to enter --no-console? or something similar?

Thanks.

**Comment by rom1v** [comment]
There is a `scrcpy-noconsole.vbs` script in the release. It runs scrcpy without the console.

https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

> And if so what command would i need to enter --no-console?

A command line parameter to not start a console would not be possible: when scrcpy is started, it's too late for Windows, the console is already open. See https://github.com/Genymobile/scrcpy/pull/1988#issuecomment-760768688.
That's why there's a separate VBS script.
