### ISSUE TITLE
Scrcpy is not supporting touch event in landscape orientation

### ISSUE THREAD

**Issue by srinikesh2929** [Genymobile/scrcpy#2854]
Scrcpy is not supporting touch event through mouse in Landscape in Android Tablet
**Environment**
 -Windows 10
 - v1.1.9
 -  Windows release
 - 
 - v21H1(OS Build 19043.1200)
 - Android version: [7]

**Describe the bug**
Scrcpy is not supporting touch event in landscape orientation

**terminal message**
```
[server] WARN: Ignore touch event, it was generated for a different device size
```

**Comment by srinikesh2929** [comment]
I want to use it in landscape. Scrcpy only supports touch event in portrait and it is forcing me to use in portrait, which I don't like...

**Comment by rom1v** [comment]
If you encounter this message, you probably have two lines on starting, similar to this:
```
INFO: Initial texture: 1080x2336
INFO: New texture: 888x1920
```

The reason is that the device sends a video stream at a size different from the requested one.

Limit the video size to what it automatically sends, and everything will work again.

See https://github.com/Genymobile/scrcpy/issues/2031#issuecomment-758567488 and a973757fd141fc07ef81314d350bd4f4de64f59c for explanations.

**Comment by srinikesh2929** [comment]
@rom1v 
How to do that?

**Comment by rom1v** [comment]
For example `scrcpy -m 1920` if the max supported dimension is 1920.

If you don't know how command line works: https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#command-line-on-windows

**Comment by srinikesh2929** [comment]
If I set it to 592, length automatically changes from 1024 to 336...

It's not working out...

**Comment by rom1v** [comment]
What did you do exactly?

**Comment by srinikesh2929** [comment]
Initial texture : 1024x600
New texture : 1024x593

I gave the command `scrcpy -m 593`

**Comment by rom1v** [comment]
`-m` means max size, so you don't want the biggest dimension to be 592 (it's probably 592, not 593, isn't it?)

The problem is that your device decides by itself to use 592 instead of 600 (because it's a multiple of 16).

Try `scrcpy -m1010`, that might force the other dimension to be 592 (but then that might cause other problems) :/

**Comment by srinikesh2929** [comment]
I tried this @rom1v .It works now, Thanks a lot..
