### ISSUE TITLE
cannot record

### ISSUE THREAD

**Issue by mikebilly** [Genymobile/scrcpy#2953]
- [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows
 - scrcpy version: 1.21
 - installation method: Windows release
 - device model: LG G6
 - Android version: 9

I tried both commands:
```scrcpy --record file.mp4```
and 
```scrcpy --no-display --record file.mp4```
but neither produced a watchable video file, I got file.mp4 but I got this error:
![image](https://user-images.githubusercontent.com/29500216/149826105-8dbeda4a-c2d3-460d-87ba-e32a35441810.png)
```
File Source (Async.)::Output

Media Type 0:
--------------------------
Unknown

AM_MEDIA_TYPE: 
majortype: MEDIATYPE_Stream {E436EB83-524F-11CE-9F53-0020AF0BA770}
subtype: Unknown GUID Name {08E22ADA-B715-45ED-9D20-7B87750301D4}
formattype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
bFixedSizeSamples: 1
bTemporalCompression: 0
lSampleSize: 1
cbFormat: 0


Media Type 1:
--------------------------
Unknown

AM_MEDIA_TYPE: 
majortype: MEDIATYPE_Stream {E436EB83-524F-11CE-9F53-0020AF0BA770}
subtype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
formattype: TIME_FORMAT_NONE {00000000-0000-0000-0000-000000000000}
bFixedSizeSamples: 1
bTemporalCompression: 0
lSampleSize: 1
cbFormat: 0


```

**Comment by rom1v** [comment]
How did you interrupt recording? On Windows, you MUST NOT close the terminal, because in that case Windows kills the program and scrcpy could not finalize the video file.

Instead you should Ctrl+C (or disconnect the device), or just close the scrcpy window.

Note that Ctrl+C to interrupt is implemented only since v1.14 on Windows (https://github.com/Genymobile/scrcpy/commit/28abd98f7fef5161ede934a41287b2c0ec1d7668).

> scrcpy version: 1.12

It's very old. Upgrade to the latest version.

**Comment by mikebilly** [comment]
@rom1v  sorry, it was a typo, I'm using version 1.21. And yes, I closed the mirrored screen when I wanted to finish recording and the video file was corrupted. Pressing Ctrc+C was the solution.

**Comment by rom1v** [comment]
> I closed the mirrored screen when I wanted to finish recording and the video file was corrupted.

You closed the mirrored screen window or the terminal? If you closed the scrcpy window, that's totally not expected.

Could you retry, please? If it's still corrupted by closing the scrcpy window (not the terminal), then please reopen the bug.

**Comment by mikebilly** [comment]
I don't remember correctly, but probably I closed the terminal instead of the screen window. I tried closing the screen window and it worked as expected. Thank you for your reply.

**Comment by rom1v** [comment]
> I tried closing the screen window and it worked as expected.

Ok, thank you :+1: I'm relieved 😌

**Comment by mikebilly** [comment]
I used this command ```scrcpy --bit-rate 30M --no-display --record file.mp4``` and this is the output video:
```
Bit rate                    : 20.2 Mb/s
Width                       : 1 440 pixels
Height                      : 2 880 pixels
Display aspect ratio        : 0.500
Frame rate mode             : Variable
Frame rate                  : 37.891 FPS
Minimum frame rate          : 2.870 FPS
Maximum frame rate          : 109.756 FPS
```
How to make it record at actual 30 Mb/s and at constant 60fps?

**Comment by rom1v** [comment]
The bitrate is passed as is to MediaCodec (which configures thr hardware encoder). Since it's live, there is little chance that the final bitrate perfectly matches the request.

The encoder produces a new frame whenever the device screen changes, so the framerate is very variable (0 fps on a static screen, 25 or 30 fps if you play a video fullscreen on your device, any other value when you scroll or any animation is displayed).
