### ISSUE TITLE
[Information request] Explanation about specific app DRM

### ISSUE THREAD

**Issue by Valkhes** [Genymobile/scrcpy#2979]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: MacOS
 - scrcpy version: 1.21
 - installation method: Brew / Using only the server and getting control and video socket data
 - device model: Pixel 2 XL, Samsung S9+
 - Android version: 10

**Describe the bug**

Hello, this is not really a "bug" (or maybe it is?) but an information request about how scrcpy is handling DRM.
Most of the time, when a DRM is happening, we have a black screen or a screen freeze using scrcpy. It is for me the normal state  as the content is protected.

I realized yesterday that on the phones I'm using with scrcpy, I was able to watch Netflix movies and series, even if Netflix is using DRM protection.

I'm starting to question myself about how this is possible, and I wanted to know if you had any information about why this is happening ? Is it a Netflix app problem, or are we trying with scrcpy to bypass DRM sometimes for any reason ?

Thanks for reading :)

**Comment by rom1v** [comment]
My knowledge about DRM is very limited, but basically there are several levels of restrictions:
 - widevine level 3 (software): I think the content is captured by scrcpy (at least before Android 12)
 - widevine level 1 (hardware): could not be captured

Normal apps without DRM could request to "protect the screen" (SECURE_FLAG). This might be useful under the control of the user (for example in Signal), but some apps do not allow to disable it (bank apps). Before Android 12, it was mirrored by scrcpy, but since Android 12 it is not possible anymore, see #2129.

**Comment by Valkhes** [comment]
Wow, thanks a lot for the quick answer, it is easy to understand now as my phones are on Android 10 and 11. That's really helpful !
