### ISSUE TITLE
Crashing when unlocking

### ISSUE THREAD

**Issue by Dimitri-UNHCR** [Genymobile/scrcpy#2995]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 10
 - scrcpy version: 1.22
 - installation method: Windows release
 - device model: Redmi Note 8 pro
 - Android version: 10

**Describe the bug**
I just migrated to v 1.22, and I have the following issue (didn't have it with 1.18):
- Connect the USB cable to the phone
- Launch scrcpy (launches and displays the lockscreen)
- unlock the phone (using pin in scrcpy window)
x scrcpy stops

If now I relaunch scrcpy, everything works normally. It is only the 1st time that scrcpy closes
The console displays: WARN: Device disconnected

Thanks

**Comment by rom1v** [comment]
> Crashing when unlocking

> The console displays: WARN: Device disconnected

It's not a "crash", it's an adb disconnection (every other adb connection would also close at the same time, for example `adb shell` or `adb logcat`).

This probably happen because some USB mode are enabled only when unlocked (MTP, etc), so unlocking resets the USB/adb connection. See https://github.com/Genymobile/scrcpy/issues/1382#issuecomment-627591729

**Comment by Dimitri-UNHCR** [comment]
Thanks.
Why does it work the 2nd time though? The unlock does the same (file transfer)
