### ISSUE TITLE
Legacy paste is limited to a certain number of characters?

### ISSUE THREAD

**Issue by Balouj** [Genymobile/scrcpy#3039]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 11
 - scrcpy version: 1.22
 - installation method: Windows release
 - device model: samsung a22
 - Android version: 11

**Describe the bug**
I'm using legacy paste to copy paste text from my pc into a database app on my android (because the normal paste method doesn't work in this app). This works fine, except that the pasted text is cut short after a certain number of characters,  equivalent to a few lines of text, when trying to copy a whole paragraph. 

Is this expected or should the whole text be pasted? Thanks

**Comment by rom1v** [comment]
With `--legacy-paste`, the text is injected as a sequence of key events.

It works correctly basically for ASCII chars (and some other accented chars). Since it takes time to inject, a limit of 300 chars is set:
 https://github.com/Genymobile/scrcpy/blob/0e22032710728baf3c78d20a53e89cba202138ec/app/src/control_msg.h#L16

This avoids to block the device for tens of seconds for injecting events.

**Comment by Balouj** [comment]
Thanks
