### ISSUE TITLE
Recording without deleting old files

### ISSUE THREAD

**Issue by Peree-x** [Genymobile/scrcpy#3116]
- [ ] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
i want to use this app to record some videos with recording function but everytime the new recording starts it deletes the old one and makes new one instead of naming it like video and video(1), it would be better if i could use something like v4l2loopback on windows and then in obs but right now it is not possible.

**Describe the solution you'd like**
When starting\ending a recording and there is a file with the same name then add (int+1) to the name.
For doing this you could make this option default one and if someone wants to remove the old file they should add -r or something
so it will be like _scrcpy -rr file.mp4_

**Describe alternatives you've considered**
When starting the recording giving it a random name and making file invisible, then when recording ends make a popup window asking for file name (if file name already exist give error). 

similar request:
https://github.com/Genymobile/scrcpy/issues/1506

**Comment by rom1v** [comment]
Yes, I have this in mind (#1506 too).

> it would be better if i could use something like v4l2loopback on windows and then in obs but right now it is not possible.

Actually, to record, it's better to use `scrcpy --record file.mp4` than recording with OBS, this avoids a decoding/re-encoding cycle.

**Comment by qaisbayabani** [comment]
it is possible and i have already done it with my own instalable server with builtin Capture a single file c# client improved version without adb and a single file server. a hint is to do it we need two steps:- 

1- We have to improve my [qaisbayabani](https://github.com/qaisbayabani)
/
[SCRCPY-C-Sharp-Client](https://github.com/qaisbayabani/SCRCPY-C-Sharp-Client)  

as it is buggy and adb included because i have to conceal original version of mine. 

a bug free disconnection free version of above said version we need.

2- An app for android a server which transmit the screen of device to the desired port of pc by improving the a screen capture excelent example **grafika screen capture** example which is excellently doing it with a huge HEADACHEING but at last succeeded and transmitting and saving the screen at same time.

I assure you i will soon publish the said Library if its not worth selling. 
Hugs

**Comment by Peree-x** [comment]
thank you for keeping this in mind i will wait for the feature.
I actually tried the --record and used script someone created to change names but the problem was that no audio was being record so to add audio i downloaded fmedia and it got complicated real soon.
so the best option for me was to use obs that records video and audio in the same time. that has a few issues because i need to scale the window with some commands and keep rotation locked but because your docs are well made it was done in under 30 min. thanks again
