### ISSUE TITLE
Standalone Binary for MacOS just like Windows 

### ISSUE THREAD

**Issue by Genxster1998** [Genymobile/scrcpy#3235]
Its very deterrent that MacOS users have to install a pathetic package manager which itself cost 3-4GB storage and take immense time to update repo like Homebrew , Macports to install scrcpy .
Is it not going to get solved #1733 
Please Close it if its not possible at all .
Others are cashing it out like paid software Wormhole for mac performing same thing essentially using scrcpy source at core .

**Comment by LeeBinder** [comment]
@Genxster1998 how do you know that Wormhole for Mac is using scrcpy source at core? Can you please share links to follow and read?

**Comment by Genxster1998** [comment]
@LeeBinder I meant with technology idea ...
You think scrcpy don't need a server or only need it to be temporarily injected in art /dalvik runtime via a jar not apk ,come on ! 
I have seen same dependencies like avcodec, avutil  avformat libs in its app supporting files .
It uses Qt but I won't say that this is a poor wrapper blatantly copy things underhood.
For windows scrcpy provides fairly standalone binary instead of pulling 2GB+ other unix dependencies packages .

**Comment by LeeBinder** [comment]
@ Romain I am sorry to see what you just found out. Did they infringe upon the Apache license you have filed scrcpy under as per that [section in your ReadMe](https://github.com/Genymobile/scrcpy#licence)? I don't see any official mention of scrcpy [anywhere throughout their website](https://www.google.com/search?q=scrcpy+site:er.run&sxsrf=ALiCzsZwp1EX_jKp3SCU3ZlZpdwHoWwsmg:1652383507512&filter=0&biw=1200&bih=602&dpr=1.33).

Their [Google Pay Store's page](https://play.google.com/store/apps/details?id=com.viper.wormhole&referrer=utm_source%3Doffiical_site) discloses their full address (in UK).

@Genxster1998 good job, you have sensitive detective whiskers!

I'm not a dev so even if I looked at the source code, I wouldn't be able to tell the exact digital magic Romain is using for scrcpy. Sure it's doing some live runtime injection into Android components via adb, otherwise it wouldn't perform, but like Romain states in the ReadMe:

`non-intrusiveness: nothing is left installed on the Android device`

@rom1v would it be of any help if you had a chance to run macOS - would that enable you to compile all the components for a stand-alone package for Mac only containing scrcpy itself + the necessary dependencies (binaries, dylds, headers etc.) analog to the nicely small Windows zip package?

**Comment by shuosiw** [comment]
sound that it's already to support Standalone Binary for MacOS? 
Good :) I also don't like installing such more dependence haha..

**Comment by Coool** [comment]
[scrcpy](https://github.com/Coool/scrcpy-macOS-Binaries) for macOS

**Comment by zhaoyueer** [comment]
@Coool could not run 'scrcpy' in Terminal. here's a hint - Could not open 'scrcpy' because the developer could not be verified

**Comment by shuosiw** [comment]
> [scrcpy](https://github.com/Coool/scrcpy-macOS-Binaries/releases) for macOS

@Coool please update v2.0 :) thx

**Comment by Coool** [comment]
@shuosiw, [scrcpy v2.0](https://github.com/Coool/scrcpy-macOS-Binaries/releases/tag/v2.0) for macOS.

**Comment by hellokuan** [comment]
> @shuosiw, [scrcpy v2.0](https://github.com/Coool/scrcpy-macOS-Binaries/releases/tag/v2.0) for macOS.
> 
> P.S. Report on which macOS version binary is working!

@Coool zsh: bad CPU type in executable: ./scrcpy ，pls support Apple silicon m1&m2，pls update，thx

**Comment by hellokuan** [comment]
@Coool  can you tell me , how to build a standalone binary for macOS(Apple silicon m1&m2)?

**Comment by t880216t** [comment]
> @shuosiw, [scrcpy v2.0](https://github.com/Coool/scrcpy-macOS-Binaries/releases/tag/v2.0) for macOS.
> 
> P.S. Report on which macOS version binary is working!

Please update to v2.2 or refer to the provided tutorial for instructions. Thank you very much.

**Comment by aeroxy** [comment]
> > @shuosiw, [scrcpy v2.0](https://github.com/Coool/scrcpy-macOS-Binaries/releases/tag/v2.0) for macOS.
> > P.S. Report on which macOS version binary is working!
> 
> Please update to v2.2 or refer to the provided tutorial for instructions. Thank you very much.

Please update to v2.4 or refer to the provided tutorial for instructions. Thank you very much.

**Comment by muvaf** [comment]
For anyone looking to build the standalone binary themselves, here is a quick [build script](https://gist.github.com/muvaf/012155379661966266c3a7b7507d262c) that I confirmed on an arm64 macOS.

**Comment by LeeBinder** [comment]
Hi @muvaf Thank you for the condensed simplifiedscript. Even when I run it on my Intel Mac right form the "root" of my user account's home directory ~, I get:

> ERROR: Neither source directory 'build-macos-static' nor build directory None contain a build file meson.build.

I do have meson installed:
```
$which meson 
/usr/local/bin/meson
$meson -v
1.6.0
```
meson also installed the latest nasm and ninja as deps, so that can't be it, either.

Changing `#!/usr/bin/env bas`h to `#!/usr/bin/env zsh` doesn't change that.

`~/build-macos-static` is empty. A `~/build` directory has not been created, but shouldn't that be the same = `build-macos-static`, too? 

Why does it complain with build directory **None**. Any idea?

**Comment by LeeBinder** [comment]
Hi @muvaf Thank you for the condensed simplifiedscript. Even when I run it on my Intel Mac right form the "root" of my user account's home directory ~, I get:

> ERROR: Neither source directory 'build-macos-static' nor build directory None contain a build file meson.build.

I do have meson installed:
```
$which meson 
/usr/local/bin/meson
$meson -v
1.6.0
```
meson also installed the latest nasm and ninja as deps, so that can't be it, either.

Changing `#!/usr/bin/env bas`h to `#!/usr/bin/env zsh` doesn't change that.

`~/build-macos-static` is empty. A `~/build` directory has not been created, but shouldn't that be the same = `build-macos-static`, too? Why does it complain with build directory **None** - any idea?

**Comment by muvaf** [comment]
@LeeBinder You need to clone this repo, copy the script into it and run it. The [meson.build](https://github.com/Genymobile/scrcpy/blob/master/meson.build) it's looking for is at the top level of this repo.

**Comment by rom1v** [comment]
Refs #5306 (we need a GitHub Actions script for macOS).

**Comment by LeeBinder** [comment]
@muvaf

1. downloaded [scrcpy-master.zip](https://github.com/Genymobile/scrcpy/archive/refs/heads/master.zip) and unpacked to ~/scrcpy-master
2. downloaded your [build script](https://gist.github.com/muvaf/012155379661966266c3a7b7507d262c) and copied it into ~/scrcpy-master
3. copied meson.build to ~
4. chmod +x ~/scrcpy-master/build.sh
5. executing build.sh

Error:

> The Meson build system
> Version: 1.6.0
> Source dir: /Users/lee
> Build dir: /Users/lee/build-macos-static
> Build type: native build
> 
> meson.build:1:0: ERROR: Unknown options: "compile_server, portable, prebuilt_server"
> 
> A full log can be found at /Users/lee/build-macos-static/meson-logs/meson-log.txt

<details>  <summary>meson-log.txt - click to expand</summary>   

```javascript  Build started at 2024-11-19T13:50:51.275475
Main binary: /usr/local/opt/python@3.13/bin/python3.13
Build Options: -Db_staticpic=true -Db_lto=true -Dportable=true -Dcompile_server=false -Dprebuilt_server=prebuilt/scrcpy-server-v2.7 -Dc_args=-I/Users/lee/deps-static/libusb-install/include -Dbuildtype=release -Dstrip=True
Python system: Darwin
The Meson build system
Version: 1.6.0
Source dir: /Users/lee
Build dir: /Users/lee/build-macos-static
Build type: native build

meson.build:1:0: ERROR: Unknown options: "compile_server, portable, prebuilt_server"  
```
</details>

Can you share the correct lines, please?

**Comment by muvaf** [comment]
@LeeBinder You don't need to copy `meson.build` anywhere. After the downloads, run the following commands in your terminal:
```bash
cd ~/scrcpy-master
chmod +x build.sh
./build.sh
```

**Comment by LeeBinder** [comment]
ah OK - YES, now it ran all the way through, and scrcpy is working just fine 💯. Thank you @muvaf - well done 👍 

Do you have any idea that this means? Do you get this warning, too?

> Found ninja-1.12.1 at /usr/local/bin/ninja
> ninja: Entering directory `build-macos-static'
> [71/71] Linking target app/scrcpy
> **ld: warning: could not create compact unwind for _kbd_window_init: stack subq instruction is too different from dwarf stack size**
> Build complete! Standalone binary is in dist/scrcpy-macos-v2.7

**Comment by rom1v** [comment]
Please test the latest macOS binary here: #5515

**Comment by LeeBinder** [comment]
For now Apple Silicon aka AArch64 (newer Macs with Mx chip) only. Latest as of Nov 23, 2024 at https://github.com/Genymobile/scrcpy/pull/5515#issuecomment-2495589621

**Comment by rom1v** [comment]
@LeeBinder Latest is the official release now 😉

**Comment by LeeBinder** [comment]
Ah OK - congrats, Romain 👍 However, the zip should correctly be labeled `scrcpy-macos-aarch64-v3.0.tar.gz` because it's not for both macOS archs.

**Comment by rom1v** [comment]
Yes, I know, same for Linux. I'll change when there will be more than 1 target released :wink:
