### ISSUE TITLE
scrcpy project virtual display

### ISSUE THREAD

**Issue by BarleyXu** [Genymobile/scrcpy#3344]
- [ ] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
I create a virtual display in App. and I want project it to PC throuth scrcpy. I have get the display id of virtual display by "adb shell dumpsys display | findstr mDisplayId=". 
then I execute
scrcpy --display  virtualId. it failed
```
[server] INFO: Device: Google AOSP on redfin (Android 11)
[server] ERROR: Exception on thread Thread[main,5,main]
com.genymobile.scrcpy.InvalidDisplayIdException: There is no display having id 2
        at com.genymobile.scrcpy.Device.<init>(Device.java:72)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:65)
        at com.genymobile.scrcpy.Server.main(Server.java:331)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
[server] ERROR: Try to use one of the available display ids:
[server] ERROR:     scrcpy --display 0
[server] ERROR:     scrcpy --display 3
ERROR: Server connection failed
```

**Describe the solution you'd like**
Does scrcpy can project virtual display to PC?

**Describe alternatives you've considered**
I open a emulator screen in Android, and It can project by scrcpy, but why the virtual display can not projected?

**Additional context**

**Comment by rom1v** [comment]
The error message is explicit:

> There is no display having id 2

> [server] ERROR: Try to use one of the available display ids:
> [server] ERROR:     scrcpy --display 0
> [server] ERROR:     scrcpy --display 3

**Comment by consp1racy** [comment]
Hi, please follow along:
* https://github.com/Genymobile/scrcpy/blob/ed84e18b1ae3e51d368f8c7bc88ba4db088e6855/server/src/main/java/com/genymobile/scrcpy/Device.java#L69
* https://cs.android.com/android/platform/superproject/+/android11-release:frameworks/base/core/java/android/hardware/display/IDisplayManager.aidl;l=35
* https://cs.android.com/android/platform/superproject/+/android11-release:frameworks/base/services/core/java/com/android/server/display/DisplayManagerService.java;drc=7acbc840668959d7d8a0ab05b33bdc3d2fcb433b;l=882
* https://cs.android.com/android/platform/superproject/+/android11-release:frameworks/base/core/java/android/view/Display.java;drc=7acbc840668959d7d8a0ab05b33bdc3d2fcb433b;l=1537

```java
public static boolean hasAccess(int uid, int flags, int ownerUid, int displayId) {
    return (flags & Display.FLAG_PRIVATE) == 0
            || uid == ownerUid // app that created the virtual display
            || uid == Process.SYSTEM_UID // 1000
            || uid == 0 // root
            // Check if the UID is present on given display.
            || DisplayManagerGlobal.getInstance().isUidPresentOnDisplay(uid, displayId);
}
```

`scrcpy` always runs from shell with UID `2000` (non-rooted) or `0` (rooted). Root has access, so you may see the display if you run `scrcpy` on a rooted device and run `adb root` beforehand.

Otherwise you'll have to declare the virtual display as public using [`VIRTUAL_DISPLAY_FLAG_PUBLIC`](https://developer.android.com/reference/android/hardware/display/DisplayManager#VIRTUAL_DISPLAY_FLAG_PUBLIC), but maybe this isn't what you intended.

**Comment by BarleyXu** [comment]
@consp1racy 
Thanks a lot! It worked after setting flag to **_VIRTUAL_DISPLAY_FLAG_PUBLIC_**

**Comment by BarleyXu** [comment]
DONE

**Comment by huynhtanloc2612** [comment]
Hi @BarleyXu 
Could you show the content of virtual display on PC with scrcpy? I am trying to create virtual display by Android app with flag of VIRTUAL_DISPLAY_FLAG_PUBLIC like you did. The display was created successfully. But the  scrcpy can show only black screen on PC. Even I can launch an app on this virtual display. I tried on Android 13 and 9 on scrcpy 2.1.1
