### ISSUE TITLE
What is the best option for scrcpy to get screenshot of device every 200ms or 500ms?

### ISSUE THREAD

**Issue by S-YOU** [Genymobile/scrcpy#3345]
- I'm currently  using screencapture on my Mac, but looking for native options from scrcpy. 
- `adb exec-out screencap` took 1.5s on my environment so it is not the option

**Comment by rom1v** [comment]
There is no "screenshot" feature implemented/merged (see #2040 #684).

However, if you want a "screenshot" every 200ms, record a video at 5 fps:

```
scrcpy --fps=5 --record=video.mkv
```

(then convert the video to images using ffmpeg)

**Comment by rom1v** [comment]
> --fps you meant is --max-fps?

Yes, sorry, `--max-fps`.

 > I somehow seeing that --max-fps=1 or 2 still seeing output of 7~10 fps with --print-fps option.

Indeed, that's surprising.

But in fact, it's due to [`KEY_REPEAT_PREVIOUS_FRAME_AFTER`](https://developer.android.com/reference/android/media/MediaFormat#KEY_REPEAT_PREVIOUS_FRAME_AFTER) ([here](https://github.com/Genymobile/scrcpy/blob/ed84e18b1ae3e51d368f8c7bc88ba4db088e6855/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java#L256)), which repeats a frame (after [100ms](https://github.com/Genymobile/scrcpy/blob/ed84e18b1ae3e51d368f8c7bc88ba4db088e6855/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java#L25) as configured) when no new frame is produced, to recover from possibly bad quality on a static frame. It's not entirely clear to me why it's does not always produce 10fps then, but maybe it avoids a new frame if it brings no changed compared to the previous encoded+decoded one.

You could disable this option by overriding the MediaCodec option:

```
scrcpy --max-fps=2 --print-fps --codec-options=repeat-previous-frame-after:string=0
```

You will not get more than 2 fps (sometimes 3 due to how it's measured by intervals on the client side, but never more).

**Comment by S-YOU** [comment]
> scrcpy --max-fps=2 --print-fps --codec-options=repeat-previous-frame-after:string=0

Thank you very much, that worked!

Also, I've hacked into decoder.c and figured a quick and dirty way to dump screenshots directly there. 
You may close this issue.

**Comment by ilove-uou** [comment]
how can i use cmd which can screenshot my phone? I want screenshot quickly and i only can use cmd
