### ISSUE TITLE
scrcpy.exe suddenly disappears from path folder

### ISSUE THREAD

**Issue by hadiwiharja** [Genymobile/scrcpy#3382]
- [v ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [v] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 11
 - scrcpy version: 1.24
 - installation method: zip download
 - device model: ASUS Adol CASE
 - Android version: 8.1.0

**Describe the bug**
scrcpy.exe file always disappear from 'platform-tools' folder after one or two sessions every day. So far I need to re-extract the archive every time it happens as temporary solution.

error code after calling scrcpy on powershell:

```
scrcpy : The term 'scrcpy' is not recognized as the name of a cmdlet, function, script 
file, or operable program. Check the spelling of the name, or if a path was included,        
verify that the path is correct and try again.
At line:1 char:1
+ scrcpy
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (scrcpy:String) [], CommandNotFoundException   
    + FullyQualifiedErrorId : CommandNotFoundException

```

**Comment by Hwiharja** [comment]
Thank you for your feedback, Romain. I never got any notifications back and even disabled my antivirus and defender and tried different folders but to no avail.

**Comment by marekcik** [comment]
> 

Hello friend, first of all I hope you can understand what I wrote because my english is not very good. Since the desktop was very full yesterday, I opened a new folder and threw them all there. I couldn't run adb when I looked today, first I found your request for help, and have a light bulb go off in my brain. Sorry i was babbling, as for your question; There should be a folder on the desktop that you set up for adb. You may have moved or deleted this folder to a different folder. I hope your problem will be solved if you can extract the "adb (scrcpy)" folder from its lair and throw it back to the desktop. Have a nice day, I hope I helped.

**Comment by hadiwiharja** [comment]
Hey Marekcik, thanks for your help. I actually managed to solve the issue due to one antivirus running in silent mode as Romain pointed. I only needed to release it from quarantine list. You too have a nice day!
