### ISSUE TITLE
screen mirroring stops after about 20-30 minutes

### ISSUE THREAD

**Issue by muvvag** [Genymobile/scrcpy#341]
if i'm mirroring the screen continuously, the app stops after about every 30 minutes. I have to open the app again .Is that normal ?

**Comment by rom1v** [comment]
If it closes, either there is a crash (check logs in the console or `adb logcat`), or the socket is closed, due to adb disconnection (itself probably caused by USB problems, check `adb devices` when it happens).

You can try to use another USB cable. See https://github.com/Genymobile/scrcpy/issues/281 and https://github.com/Genymobile/scrcpy/issues/283.
