### ISSUE TITLE
Spelling marks showed as two distinct characters ("aáaâaä")

### ISSUE THREAD

**Issue by RafaelLinux** [Genymobile/scrcpy#3450]
- [X] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [X] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [e.g. Debian, Windows, macOS...]
 - scrcpy version:  1.24
 - installation method: RPM
 - device model: Samsung S20 FE
 - Android version: 10

**Describe the bug**
Letters containing auxiliary spelling marks (', ¨ , ^ ) appear incorrectly in Android screen after typing them from the computer. If the user types "áâä" on the computer, "aáaâaä" appears on the screen of the Android device.

```
Please paste terminal output in a code block.
```

**Comment by rom1v** [comment]
Use `scrcpy --prefer-text`.

**Comment by RafaelLinux** [comment]
Oh, sorry. I didn't search for "latin accents" so this is clearly a duplicate issue (https://github.com/Genymobile/scrcpy/issues/650#issuecomment-512945343)

Thank you for info.

I expect this will be fixed when you have time.

Your application is AWESOME, THANK YOU

**Comment by rom1v** [comment]
> I expect this will be fixed when you have time.

There is no "bug", just use `scrcpy --prefer-text` to get the behavior you want.

**Comment by rom1v** [comment]
The problem is that with input event injection, there is no "one-size-fits-all" solution:

Concretely, if I press a, do we want to inject a key event "A pressed" then "A released", or the text "a"? It depends:
 - if I am playing a game, I want the key events, so that WASD work correctly: we must preserve the time when the key is pressed and the time when it is released;
 - if I am typing text, I want text events, so that typing `^` then `a` sends `â` (the combination does not necessarily works the same on the client and the mirrored device).

For letters and space, the default behavior in scrcpy is to send key events, as injecting keys for letters or space generate the correct text in most cases, and does not break WASD (or other shortcuts) in games. However, this breaks accented characters for example: for example `^` + `e` generates `eê` (`e` due to the key pressed/release and `ê` due to the text event). Therefore, scrpcy has a flag (`--prefer-text`), which makes it work correctly for accented characters, but breaks the expected WASD behavior.

**Comment by RafaelLinux** [comment]
Perfect and detailed explanation, thank you very much.
Another thing will be that I remember to set the parameter when I intend to
play :(

I take this opportunity, if I haven't already done so, to thank you for
your excellent work, the truth is that it is surprising how much your
program allow us to do.

Regards
