### ISSUE TITLE
Lagging and freezing in display window

### ISSUE THREAD

**Issue by Monkeytron** [Genymobile/scrcpy#3474]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Windows 11
 - scrcpy version: 1.24
 - installation method: Windows release
 - device model: Moto G(6) Play
 - Android version: 9

I am having some problems with lag and dropped frames when running scrcpy to capture in OBS. My phone does not seem to be lagging in the game when scrcpy is active, but the window that displays it on my computer which I am recording with OBS keeps freezing and lagging hugely.

This is not a constant problem - usually everything works fine - but when it starts randomly during recording the only consistent solution I have is to completely restart my phone. I am using USB connection so the problem is probably with the performance of my phone/PC rather than the connection.

Does scrcpy run any processes on my phone's CPU, or is it all on the computer? If I know what device the lag originated on, that might help me to fix this problem.

I am running [scrcpy -d --max-fps 30 -b 2M -m 1280] in the command prompt window, to get 30fps 720p resolution.

**Comment by rom1v** [comment]
If you don't run OBS, does it lag?

Capturing the window via OBS can introduce lags due to shared resources on the computer.

On Linux, you could use [v4l2](https://github.com/Genymobile/scrcpy#v4l2loopback) and capture the V4L2 stream via OBS (this avoids to render in a Windows then capture the window).

> Does scrcpy run any processes on my phone's CPU, or is it all on the computer? If I know what device the lag originated on, that might help me to fix this problem.

Record the stream:

```
scrcpy --record file.mp4
```

If the resulting video file is laggy, then the lag occurs on the device. Otherwise, the lag occurs on the computer. Using `--print-fps` might also help to find out the cause.

**Comment by Monkeytron** [comment]
Thank you very much.

Unfortunately capturing via obs is not avoidable for how I use scrcpy (live streaming / recording audio with video etc), but I will experiment with those suggestions if I encounter the lag again.
