### ISSUE TITLE
Add bash completion script to scrcpy installation (script included here)

### ISSUE THREAD

**Issue by animaone** [Genymobile/scrcpy#3522]
- [ x] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

**Is your feature request related to a problem? Please describe.**
Related to the completion of device id for when you are using multiple devices.

**Describe the solution you'd like**
When typing scrcpy -s + TAB_KEY there is no bash completion for the device id. There is already a bash script for adb. What I've done is copying the adb script and made some modifications to it.

**Describe alternatives you've considered**
The current alternative is copying devices ids manually or typing adb -s + TAB_KEY, then changing the adb command to scrcpy

**Additional context**
I've attached the script. Just EXTRACT IT and copy it to /etc/bash_completion.d/ and enjoy!
[scrcpy.tar.gz](https://github.com/Genymobile/scrcpy/files/9729338/scrcpy.tar.gz)
It would be very nice if this script(or a similar/cleaner version) could be installed automatically with the scrcpy installation.

**Comment by rom1v** [comment]
scrcpy already has [bash completion](https://github.com/Genymobile/scrcpy/blob/master/app/data/bash-completion/scrcpy) and [zsh completion](https://github.com/Genymobile/scrcpy/blob/master/app/data/zsh-completion/_scrcpy) scripts.

I agree that they should be improved so that the `-s` option is completed by the available devices exposed by `adb devices`.

**Comment by animaone** [comment]
Thanks. I've made a pull request with the modification in the default bash_completion script.
https://github.com/Genymobile/scrcpy/pull/3523
