### ISSUE TITLE
device unauthorized.

### ISSUE THREAD

**Issue by cordac1** [Genymobile/scrcpy#354]
Huawei Mate 20 Pro

Dev Settings/USB Debugging = on

I get this:

```
adb: error: failed to get feature set: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.
ERROR: "adb push" returned with value 1
Press any key to continue...

PS C:\scrcpy-win64> adb devices
List of devices attached
adb server version (40) doesn't match this client (39); killing...
* daemon started successfully
LHS7N*************        unauthorized

PS C:\scrcpy-win64>
```

**Comment by rom1v** [comment]
You have two problems here:
 1. You already have some adb daemon v39 running on your computer (something which uses `adb`). If this running daemon is not reexecuted as soon as it is killed, executing `adb devices` one more time should not print `adb server version (40) doesn't match this client (39); killing...`. You should find the software which executes `adb` v39.
2. Device is `unauthorized` if you didn't authorize the connection on your device. A popup should open when you connect a device via `adb`. Some buggy devices don't always show this popup immediately. In that case, try `adb kill-server; adb start-server`, unplug-replug, and if nothing works, use an old `adb` (v39 or v36).

**Comment by cordac1** [comment]
Sorted!
Figured it out and all is good now.

Thanks alot!

**Comment by oujibahei** [comment]
I am a newbird,so I can't understand what should I do.

**Comment by billion-yash** [comment]
I will suggest trying all solution given above

and then try this
if you are using ubuntu then go to home/.android and delete the adbkey then try above steps again like adb kill-server 
this should work now.

**Comment by rodrigoli0** [comment]
bro can you help with a doubt of mine? how can I take my device from unauthorized only with cmd commands. why the screen of my phone this all destroyed I used it by scrcpy most of nowhere stopped mirroring and began to appear this unauthorized always and I can not enable by the phone why the screen is broken as I allow to device only using cmd or other commands that my Windows support ? please any answer or explain whether of the right or not

**Comment by rom1v** [comment]
If the device is in `unauthorized` state as listed by `adb devices` (i.e. if USB debugging is enabled but not allowed on the device), then you can do the following steps.

 1. plug the device: this will open a popup (that you don't see if your screen is broken)
 2. run `scrcpy --otg` (see [OTG](https://github.com/Genymobile/scrcpy#otg))
 3. press <kbd>Tab</kbd>, <kbd>Enter</kbd>, <kbd>Tab</kbd>, <kbd>Tab</kbd>, <kbd>Enter</kbd> (this enables _"Always allow from this computer"_ and click on OK)

Now your device is authorized. You can run `scrcpy`.

**Comment by rodrigoli0** [comment]
this giving this error INFO: Killing adb daemon (if any)...
ERROR: I didn't find any USB devices when I ran the command. and yet yes remains unauthorized. remembering that my phone's screen is totally broken over with USB debugging turned on. any more way i can leave from unauthorized to device.

**Comment by rom1v** [comment]
Oh, due to USB limitations on Windows, OTG mode does not work when USB debugging is enabled: #3050.

You should try on Linux (even a live USB of the latest Ubuntu is sufficient).

**Comment by rodrigoli0** [comment]
ok thank you very much

**Comment by shivagnihotri** [comment]
> If the device is in `unauthorized` state as listed by `adb devices` (i.e. if USB debugging is enabled but not allowed on the device), then you can do the following steps.
> 
> 1. plug the device: this will open a popup (that you don't see if your screen is broken)
> 2. run `scrcpy --otg` (see [OTG](https://github.com/Genymobile/scrcpy#otg))
> 3. press Tab, Enter, Tab, Tab, Enter (this enables _"Always allow from this computer"_ and click on OK)
> 
> Now your device is authorized. You can run `scrcpy`.

Greetings from Paraguay, everyone! I am currently facing the same situation as mentioned: The screen of my device is broken and I only see black. I'm on ParrotOS Linux and getting the following message from scrcpy:

`┌─[✗]─[shivagnihotri@parrot]─[~]
└──╼ $scrcpy --otg
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
ERROR: Could not find any USB device
┌─[✗]─[shivagnihotri@parrot]─[~]
└──╼ $adb devices
adb server version (39) doesn't match this client (41); killing...
* daemon started successfully
List of devices attached
S6MQ0215J5XXXXX	device
`
Is there a way to make scrcpy to require any authentication since it seems like I cannot authenticate my decice?

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#conflicts-between-adb-versions

(note: if you use the snap version, I suggest you try a non-snap version to use the same adb)

**Comment by shivagnihotri** [comment]
> https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#conflicts-between-adb-versions
> 
> (note: if you use the snap version, I suggest you try a non-snap version to use the same adb)

Thanks. I had used the version I could install with apt-get before, but it's old at version 1.17-1...

**Comment by rom1v** [comment]
> Thanks. I had used the version I could install with apt-get before, but it's old at version 1.17-1...

Either upgrade your distrib, or install the latest version of scrcpy manually: https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple

**Comment by ThePredators** [comment]
Hello, 

i'm facing the same issue my screen is broken but typing otg command and the `keyboord : Tab, Enter, Tab, Tab, Enter` doesn't seem to do anything i don't get any error and i have to stop `scrcpy --otg` command my self to check. 

Its really strange ! 

```
❯ scrcpy --otg                                                                                                                     ─╯
scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
2023-02-01 19:05:03.279 scrcpy[15478:226837] INFO: USB device: LHS7N18C21009775 (12d1:107e) HUAWEI LYA-L29
^C
```

**Comment by Taylor-eOS** [comment]
> If the device is in `unauthorized` state as listed by `adb devices` (i.e. if USB debugging is enabled but not allowed on the device), then you can do the following steps.
> 
>     1. plug the device: this will open a popup (that you don't see if your screen is broken)
> 
>     2. run `scrcpy --otg` (see [OTG](https://github.com/Genymobile/scrcpy#otg))
> 
>     3. press Tab, Enter, Tab, Tab, Enter (this enables _"Always allow from this computer"_ and clicks on OK)
> 
> 
> Now your device is authorized. You can run `scrcpy`.

I got this blind Tap pressing in OTG mode to authorize usb debugging to work twice, but now it won't work again. I had to run it from a ubuntu libe disk to get the 1.25 version. It's really cumbersome. To unlock your phone klick the mouse, then press pace, then type your pin, then enter. Luckily I could test whether I'm in lock screen because my torch is set to long press when in lock screen. As for the ok on theusb debugging prompt, I guessed around a bunch and cant remember the combination.
Since casting phones with broken screens is the most obvious use casefor scrcpy, it would be cool if there was a command to recognize these prompts and klick ok in them.

**Comment by havil88** [comment]
hi, im connect but error
C:\Users\warta\Desktop\nhieudt\scrcpy-win64-v2.3.1>scrcpy --serial R58RC3VZJ0F
scrcpy 2.3.1 <https://github.com/Genymobile/scrcpy>
ERROR: Device is unauthorized:
ERROR:     -->   (usb)           R58RC3VZJ0F      unauthorized
ERROR: A popup should open on the device to request authorization.
ERROR: Check the FAQ: <https://github.com/Genymobile/scrcpy/blob/master/FAQ.md>
ERROR: Server connection failed

**Comment by lazynoda** [comment]
> If the device is in `unauthorized` state as listed by `adb devices` (i.e. if USB debugging is enabled but not allowed on the device), then you can do the following steps.
> 
> 1. plug the device: this will open a popup (that you don't see if your screen is broken)
> 2. run `scrcpy --otg` (see [OTG](https://github.com/Genymobile/scrcpy#otg))
> 3. press Tab, Enter, Tab, Tab, Enter (this enables _"Always allow from this computer"_ and clicks on OK)
> 
> Now your device is authorized. You can run `scrcpy`.

In my case I've used `Space` instead of `Enter`. Apart from that, thank you @rom1v and scrcpy for saving my life and 43GB of memories ❤️

**Comment by ch-hassansaeed** [comment]
In my case 
 "Settings" > "Developer options" > "Revoke USB debugging authorizations"
then I disable USB debugging Mode 
and then enabled again in this case it will ask allow for this pc or machine then after that unauthorized error remove for me 
and it is working fine :)
good luck for you

**Comment by mukundzare** [comment]
> If the device is in `unauthorized` state as listed by `adb devices` (i.e. if USB debugging is enabled but not allowed on the device), then you can do the following steps.
> 
>     1. plug the device: this will open a popup (that you don't see if your screen is broken)
> 
>     2. run `scrcpy --otg` (see [OTG](https://github.com/Genymobile/scrcpy#otg))
> 
>     3. press Tab, Enter, Tab, Tab, Enter (this enables _"Always allow from this computer"_ and clicks on OK)
> 
> 
> Now your device is authorized. You can run `scrcpy`.

I have a oneplus 6 which fell flat on its face and the display has gone blank and is probably unresponsive. I already had USB debugging enabled but since running scrcpy needs authorization, I tried the steps above but it seems to not work. I tried both variants by replacing Space and Enter key too. What should I do?

**Comment by lazynoda** [comment]
@mukundzare I'd recommend to find someone else with the same phone so you can see and replicate the steps to authorize. Maybe it's different from my phone (Pixel 5).

Steps were:
- First tab to move focus on the "always allow" checkbox.
- Enter (or Space) to tick the checkbox.
- Tab moves focus to Deny (first button of the dialog)
- Another tab moves focus to Allow (second button).
- Enter to tap on the Allow button.

I'd also say buy the screen and fix it, but seems a bit expensive imho.

**Comment by mukundzare** [comment]
Firstly, thank you @lazynoda for commenting at all! I am considering buying a new display. It makes no sense to break my head with this for hours now.. I don't know anyone who has a oneplus 6 and would have the patience to help me out here.

**Comment by kralcak** [comment]
> If the device is in `unauthorized` state as listed by `adb devices` (i.e. if USB debugging is enabled but not allowed on the device), then you can do the following steps.
> 
> 1. plug the device: this will open a popup (that you don't see if your screen is broken)
> 2. run `scrcpy --otg` (see [OTG](https://github.com/Genymobile/scrcpy#otg))
> 3. press Tab, Enter, Tab, Tab, Enter (this enables _"Always allow from this computer"_ and clicks on OK)
> 
> Now your device is authorized. You can run `scrcpy`.

I had to press : Enter, Tab, Tab, Tab, Enter

**Comment by Mr-Kekmann** [comment]
This worked for me: Huawei Mate 20 Lite 
1. Make sure you unlock your device (my fingerprint still worked so this was easy, but with OTG should also be fairly easy. I read using "arrow up" a few times brings up the number pad, then enter your code and confirm).
2. Once you unlock your phone, plug in your cable from the PC.
3. Your Phone will pop up a window to ask if you want to allow access from your PC to your phones data. Activate Scrcpy otg. Press "arrow up" then "space". (This allows access to your phones storage. My phone disconnected and reconnected after this step so it should be a good indicator wether your inputs worked. Also afterwards you should be able to acces your phones "hard drive" from your PC)
4. Now start Scrpy via Console to trigger the pop-up for "permition for acces via debugging". 
5. Next use scrcpy otg again. Press "arrow up" then "space" (this will set the marker for "always allow access") Follow up by pressing "arrow down", then "arrow right" and then "space" (to confirm the Choice).
6. Now start scrcpy. Hope this works for some of you. 

Otherwise short form: follow the steps from people above but press: Arrow up, Space, Arrow down, Arrow right, Space. 

Note: I solved it by plugging in my old phone wich had a still working screen. I enabled debugging etc. Then watched step by step wich windows pop-up and wich keyboard inputs from scrcpy otg I had to make to give access for my pc. 
Wish you good luck!
