### ISSUE TITLE
Cannot control android device when move the screen into external monitor.

### ISSUE THREAD

**Issue by VVictorWang** [Genymobile/scrcpy#355]
I installed scrcpy in my macbook pro, and it runs well. I can control my connected Android device with my macpro, such as clicking some icons, inputing some words and etc. But when I moved the scrcpy screen into my external monitor conntected with my mac, I cannot control my Android device anymore!
```
scrcpy --version
scrcpy v1.4

dependencies:
 - SDL 2.0.8
 - libavcodec 58.35.100
 - libavformat 58.20.100
 - libavutil 56.22.100
```
mac OS version:  mac OS 10.14.1
Hope for your reply！
Thanks！

**Comment by rom1v** [comment]
> But when I moved the scrcpy screen into my external monitor conntected with my mac, I cannot control my Android device anymore!

I think this is the same problem as https://github.com/Genymobile/scrcpy/issues/15: clicks do not occur at the right location due to hidpi.

This bug is maybe solved in [SDL 2.0.9](https://github.com/Genymobile/scrcpy/issues/15#issuecomment-437667745) by commit [`metal: Fix high dpi and resizing on macOS, and clean up iOS code. Fixes bug #4250.`](https://hg.libsdl.org/SDL/rev/758d4e1222a7?revcount=460), but nobody tested yet.

SDL 2.0.9 is not packaged in homebrew yet (see https://github.com/Homebrew/homebrew-core/pull/33781).
