### ISSUE TITLE
Quirks with scrcpy wireless

### ISSUE THREAD

**Issue by wordlessly** [Genymobile/scrcpy#381]
Hi,

scrcpy is just an amazing piece of software! This is overall a feature request and also possibly a bug report.

I wonder if this behavior is normal. the server.jar is pushed every time I connect to my smartphone. Also scrcpy seems to be confused because there are two devices despite explicitly specifying the IP. Also there are confusing adb ERRORs and WARNINGs.

```
./run x -s 192.168.178.24:5555
/home/nemo/Desktop/scrcpy/x/server/scrcpy-server.jar: 1 file pushed. 0.9 MB/s (19174 bytes in 0.021s)
error: more than one device/emulator
ERROR: "adb reverse" returned with value 1
WARN: 'adb reverse' failed, fallback to 'adb forward'
INFO: Initial texture: 768x1280
```

The process to use 'wireless' is first to connect via USB and then establish a adb connection via tcpip. How long will this connection be active? It will be shut down when I log out or shut down my PC or if I somehow disrupt the wireless connection (e.g. by moving the smartphone to far away from the router) or by shutting down the smartphone.
Then I have do the USB setup again before using wireless, correct?

Could there be an easier way to establish the wireless connection without USB? Maybe the server.jar could do that somehow by running at smartphone startup (many apps do this). Or maybe a small app/apk could establish the adb/tcpip bridge via a single touch.

Sometimes (every ~10 presses on the home or back button or right mouse button) I get this error killing scrcpy entirely:
ERROR: Exception on thread Thread[main,5,main]

**Comment by rom1v** [comment]
> I wonder if this behavior is normal. the server.jar is pushed every time I connect to my smartphone.

Yes.

>     error: more than one device/emulator
>     ERROR: "adb reverse" returned with value 1
>     WARN: 'adb reverse' failed, fallback to 'adb forward'

This is expected. See https://github.com/Genymobile/scrcpy/commit/1038bad3850f18717a048a4d5c0f8110e54ee172 and https://github.com/Genymobile/scrcpy/issues/5.

> How long will this connection be active?

The connection is managed by _adb_, not _scrcpy_. It will be active until either you `adb disconnect`, kill the adb server, switch to _tcpip_ or unplug the cable.

> Then I have do the USB setup again before using wireless, correct?

Once you switch your device to _tcpip_ mode, your just need to `adb connect` if you loose the connection (without using USB, unless you reboot your device).

> Could there be an easier way to establish the wireless connection without USB?

For now, wireless connection relies on how _adb_ works, because we need to connect via _adb_ to get `shell` permissions. Maybe some scripts could "automate" adb wireless commands, but this would not be very reliable.

> Sometimes (every ~10 presses on the home or back button or right mouse button) I get this error killing scrcpy entirely:
> ERROR: Exception on thread Thread[main,5,main]

Oh, this is bad. Please open a new issue, with the complete stack trace after `Exception on thread Thread[main,5,main]` in the output of `adb logcat`.
