### ISSUE TITLE
(!av_read_frame(format_ctx, &packet)

### ISSUE THREAD

**Issue by Justsos** [Genymobile/scrcpy#403]
Blogger, hello, after I received the video stream, the size of AVPacket package was always 13 (code: while (! Av_read_frame (format_ctx, & packet).) which led to the normal Android screen displayed on the PC side. About a minute apart, there was a normal frame of video stream data, and the video on the PC side displayed normally. Have you ever encountered this problem? Thank you!

**Comment by rom1v** [comment]
Here:

https://github.com/Genymobile/scrcpy/blob/v1.5/app/src/decoder.c#L207

?

> the size of AVPacket package was always 13

`packet->size == 13`? ([AVPacket](https://ffmpeg.org/doxygen/2.8/structAVPacket.html))

> which led to the normal Android screen displayed on the PC side

What do you mean by "normal Android screen"?

> there was a normal frame of video stream data

compared to "normal frame of video stream data"?

Sorry, I'm not sure to understand what the problem is.

**Comment by rom1v** [comment]
> May I add your contact information?

Here is the best way to contact me about a problem in _scrcpy_ :wink:
