### ISSUE TITLE
Scrcpy.exe cannot view the Port forwarding list

### ISSUE THREAD

**Issue by ITBOYLIN** [Genymobile/scrcpy#4071]
Why is there no data after starting scrcpy.exe and running adb.exe forward -- list? How does scrcpy receive screen data?

**Comment by rom1v** [comment]
1. scrcpy executes `adb forward` (or `adb reverse`) to redirect a local port to a device socket/port (or the reverse).
2. the client can then connect (or listen) to establish the TCP connection with the device
3. once the connection is established, there is no need to keep the port redirection, so scrcpy calls `adb forward --remove` (or `adb reverse --remove`), that's why the redirection in `adb forward --list` (or `adb reverse --list`) is visible only for a few hundred milliseconds.

**Comment by ITBOYLIN** [comment]
@rom1v  Thank you. I want to display screen data in my VB program, but I can't find a good DLL that can decode H264 raw streams. Is there a recommended H264 decoding project?
