### ISSUE TITLE
`scrcpy --help` not working on Windows 10 (x64)

### ISSUE THREAD

**Issue by MiracleXYZ** [Genymobile/scrcpy#41]
After downloading the prebuilt version on Windows and putting it to PATH, `scrcpy` works fine but the helping command `scrcpy --help` doesn't work. I don't know if it's a bug.
![image](https://user-images.githubusercontent.com/30370926/37255093-68a33960-2582-11e8-9751-f8d37ffcd734.png)

**Comment by elig0n** [comment]
Windows/DOS use / for command line arguments *but* I suspect that because the arguments parsing source code function getopt_long() is only POSIX compatible it will not work at all. The fact that the same executable responds to arguments on WSL (Bash on Ubuntu) only strengthen my suspicion. 
Maybe we could use something like : https://github.com/alex85k/wingetopt 
I was trying to get into that earlier but ran into some problems with setting & employing meson & ninja on Windows...

**Comment by rom1v** [comment]
See the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#on-windows-i-have-no-output-in-the-console).

**Comment by Ruhul768** [comment]
Hi

**Comment by wingoku** [comment]
@rom1v I tried running the scrcpy command in **mingw64** console however there is _no output_ there either. I tried it inside **powershell** as well but it's of no use. I tried running the executable with double click as well but it went all in vain. 

I've added scrcpy exe in the system path as well.

```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.16299 N/A Build 16299
```

**Comment by rom1v** [comment]
> I tried running the scrcpy command in mingw64 console

`mingw64` bundled with MSYS2?

**Comment by wingoku** [comment]
@rom1v I've got the output for scrcpy --help using git bash terminal. IDK for some reason the scrcpy never dumped any output in the cmd, powershell & mingw64 terminals. However when I run ./scrcpy.exe in the git bash terminal, it returns:
`
ERROR: "adb push" returned with value 1`

I figured that's probably because of the scrcpy.exe pushing the server.jar inside `/data/local/tmp` on my phone, so I manually copied it in the mentioned directory, killed adb server and ran ./scrcpy.exe again and got the same adb error mentioned above.

IDK how to fix this problem.

**Comment by rom1v** [comment]
> However when I run ./scrcpy.exe in the git bash terminal, it returns:
>
>      ERROR: "adb push" returned with value 1

Try with:

    SCRCPY_SERVER_PATH=/path/to/the/server.jar scrcpy

Or from the _scrcpy_ root directory:

    ./run x

**Comment by rom1v** [comment]
> The second command you mentioned is invalid or may be I missed something integral related to the second command.

In `./run x`, the `x` is your meson builddir (I use `x` in the README).

Read the `run` script in the project root directory.

>  it dumped the same adb error

What if you `adb push` it manually?

**Comment by rom1v** [comment]
adb push -s 4d5dda85 scrcpy-server.jar /data/local/tmp/scrcpy-server.jar

**Comment by wingoku** [comment]
Yep I already had tried that and it gives the exact same adb copy error as mentioned above.

**Comment by ambhaiji** [comment]
The way powershell works is without an extension file it will search for a powershell applet with that name either run as .\scrcpy [options] or type cmd and enter in powershell to turn it to a Command Prompt Window

**Comment by ambhaiji** [comment]
adb push errors are common if you have adb in path having a different version with adb inside the scrcpy folder see #209

**Comment by rom1v** [comment]
Since the windows version is cross-compiled from Linux (since v1.2), it works.
