### ISSUE TITLE
Error Opening scrcpy

### ISSUE THREAD

**Issue by damothegod** [Genymobile/scrcpy#410]
Currently using a Fire HD 10 tablet on v1.6
scrcpy worked perfectly fine on another android device.

![2](https://user-images.githubusercontent.com/47043625/51775181-d624f000-20c2-11e9-80c5-ca4679342d51.png)

![1](https://user-images.githubusercontent.com/47043625/51775119-a1189d80-20c2-11e9-89ea-649b6601b609.png)

**Comment by rom1v** [comment]
Maybe your hardware encoder does not support this definition.

You could try with a lower one:

    scrcpy -m 1024
    scrcpy -m 800

**Comment by drosengarden** [comment]
Can anyone confirm if scrcpy works on Fire HD 10? And with the new 2019 version out, should I expect scrcpy to work with that new Fire OS devices or is it possible it won’t work?

**Comment by rayrayrayyyym** [comment]
@drosengarden i can confirm `scrcpy -m 1024` works on the fire hd 10 2019 version

**Comment by drosengarden** [comment]
> @drosengarden i can confirm `scrcpy -m 1024` works on the fire hd 10 2019 version

Thanks - I should have come back to indicate that I moved forward with the Fire HD 10 2019. In order to get 1920x1080, I had to change the screen size settings on the actual device. Sure, I get a small black bar at the top and bottom of the screen on the device, but it is not noticeable. The good thing is, however, by doing this, I get full HD resolution when recording the scrcpy capture through OBS.

**Comment by drosengarden** [comment]
I should also add, that using a specific USB HUB (with Multi TT chip) I am able to capture 7 devices on a single, relatively aged PC without any lag or concern. I use OBS to do scene switches between the game play of the seven people playing at the same time.

**Comment by wasantosfi** [comment]
Hi all, I can confirm **scrcpy -m 1280** works on the Fire HD 10 2021 (Brazil) version
Using an old ASUS notebook with screen as 1366x768
Looks stable and no delay noticed for now.
