### ISSUE TITLE
Is it possible to send file to PC via usb line and keep the scrcpy window alive?

### ISSUE THREAD

**Issue by kkxg** [Genymobile/scrcpy#4123]
I know it can send files from PC to Android phone. And it works great.
I am wondering if it is possible to send files from an Android phone to my computer?

When I use it to send the screen to the computer, it uses the "charge battery option"
When I change it to a "file management option" (to make my computer recognize it as a file disk then I can send files to PC), the scrcpy window is killed.

anyway its not a big problem just kind of annoying:)

**Comment by kkxg** [comment]
![image](https://github.com/Genymobile/scrcpy/assets/20535377/3c20f50e-364b-4c83-aee4-10c3fbadee95)

**Comment by nnnpa31** [comment]
I think you can start scrcpy in file mode directly.
This is no method to keep scrcpy alive when switch modes.
Switching modes causes the phone to disconnect the USB connection, thus cause scrcpy to stop working.

Chinese version:
我建议你直接开启传文件模式再启动 scrcpy
你在手机上切换模式的时候 USB 连接会直接断开， scrcpy 没有办法在 USB/ADB 断开时保持连接

**Comment by kkxg** [comment]
> I think you can start scrcpy in file mode directly. This is no way to keep scrcpy alive when switch modes. Switching modes causes the phone to disconnect the USB connection, thus cause scrcpy to stop working.
> 
> Chinese version: 建议直接开启传文件模式再启动 scrcpy 你在手机上切换模式的时候 USB 连接会直接断开， scrcpy 没有办法在 USB/ADB 断开时保持连接

Thank you.  It works!

**Comment by nnnpa31** [comment]
I apologize for not being able to assist you. I attempted to connect to the adb server using Python and listen for device connection events in order to automatically restart scrcpy when USB is disconnected and connected again. However, this approach proved to be feasible but resulted in the scrcpy window "flashing" (auto closing and opening) when the device switched modes, which is not an ideal solution.
