### ISSUE TITLE
Support displaying background tasks in scrcpy

### ISSUE THREAD

**Issue by miaobuao** [Genymobile/scrcpy#4168]
- [ ] I have checked that a similar [feature request](https://github.com/Genymobile/scrcpy/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature+request%22) does not already exist.

Description:
Currently, scrcpy is an excellent tool for mirroring the screen of an Android device to a computer. However, it only displays the active foreground screen, and there is no way to view or interact with background tasks running on the device.

Feature Request:
I would like to request the implementation of a feature that allows scrcpy to display background tasks as well. This would be particularly useful for developers and testers who need to monitor the behavior of their apps when they are running in the background.

Possible Implementation:
One possible implementation could be to introduce an option or a command that enables the display of background tasks in scrcpy. When this option is enabled, scrcpy would continuously capture and mirror the screen of the device, including any background tasks that are currently running. This would provide a more comprehensive view of the device's activity and help in identifying any issues or bugs related to background tasks.

Benefits:
1. Developers and testers can monitor the behavior and performance of their apps when they are running in the background.
2. It would enable better debugging and identification of issues related to background tasks.
3. Provides a more comprehensive view of the device's activity, improving overall testing and troubleshooting capabilities.

Additional Notes:
It's important to consider any potential performance implications or limitations of capturing and displaying background tasks. Implementing this feature may require collaboration with the Android OS or utilizing specific APIs to access background tasks.

Thank you for considering this feature request. I believe it would greatly enhance the functionality of scrcpy and make it an even more valuable tool for Android developers and testers.

**Comment by CheerfulPianissimo** [comment]
I don't think you could display background apps because the OS doesn't actually render them when they are in the background.  I don't know if there is way to tell the Android to do that. 

What you *could* do is to simulate a secondary display, move your background task to that display and then use the --display switch on scrcpy to render that display. The option for simulating a secondary display was found in the developer options of my Android 12 Samsung. I tried doing something of the sort a while ago but was met with failure because the secondary display simulation on most vendors can be described as experimental at best and I couldn't actually find a way to move apps onto there.

**Comment by miaobuao** [comment]
Thank you for your answer :)
