### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by sajjadjaved01** [Genymobile/scrcpy#427]
I'm using P8 Lite with Oreo 8.0 .
showing black screen on lock screen, if i draw pattern or enter password it shows on real devices screen.

info: how to use keyboard with game (Shadow fight 3) in scrcpy.

**Comment by rom1v** [comment]
Which version of scrcpy?

**Comment by sajjadjaved01** [comment]
using 1.5 now also checked latest(1.6).

**Comment by rom1v** [comment]
If the screen is black only for some activities (or lock screen), I guess it's due to "secure content", which is now mirrored in 1.6 (since https://github.com/Genymobile/scrcpy/commit/1fdde490fd2a0b89680a2b5da5e5274192398023) (except if it uses a hardware DRM ike Widewine L1, which is unlikely for a lock screen).

**Comment by sajjadjaved01** [comment]
just for lock screen for now.

**Comment by BaconCatBug** [comment]
Is there a way to disable this secure flag?

**Comment by rom1v** [comment]
> Is there a way to disable this secure flag?

No. Why do you want to disable it?

**Comment by BaconCatBug** [comment]
It's just annoying to have to unlock it with the actual phone when it locks
itself. I thought it wouldn't be disableable but I thought I'd ask!

**Comment by rom1v** [comment]
@BaconCatBug But the "secure" flag on the display allows to see content instead of black screen when possible. Disabling it would just cause black screens in more situation. So you don't want to disable it.

But now I get it: you don't want black screen on your lock screen. I don't know how.
