### ISSUE TITLE
[feature request] make otg mirrors the screen

### ISSUE THREAD

**Issue by bulieme** [Genymobile/scrcpy#4290]
please can someone do this?

**Comment by rom1v** [comment]
If you mean using the HID keyboard/mouse while mirroring, just use `scrcpy -KM` (see [doc](https://github.com/Genymobile/scrcpy/blob/master/doc/hid-otg.md)).

If you mean without USB debugging at all, it's not supported (it would require a preinstalled app and communicate differently, so that's out of scope).
