### ISSUE TITLE
Treat Mouse 4 the same as pressing back

### ISSUE THREAD

**Issue by lbenedetto** [Genymobile/scrcpy#430]
Many mice have extra side buttons. For example, most have a button that shows up as "Mouse 4" (Mouse 1 is left click, Mouse 2 is right click) that works to go back in most applications. In a web browser, it would be the previous page. In Android Studio, it takes you back to last line the cursor was on.

For scrcpy, it should be the same as pressing back in Android.

I'd be happy to look into doing a pull request with this feature if you could point me to the right file in the repo to use as a jumping off point.

**Comment by rom1v** [comment]
Right-click is already mapped to Back (since a right-click is almost useless on Android).

**Comment by blintwave** [comment]
Personally I would like to see an option to adjust right click, now it only is used to go back in every app but not as an actually right click. For example...Running Steam link on android you can stream games from your pc, while playing a game and you use right click on your mouse it closes or goes back in steam link app. Otherwise if you can adjust the right click to send an actually right click it would be understood inside steam link app as well and also inside the game youre streaming.

**Comment by ariona** [comment]
is there any config file to remap the mouse buttons?

**Comment by rom1v** [comment]
> is there any config file to remap the mouse buttons?

No, there isn't.

I guess this should work:

```diff
diff --git a/app/src/input_manager.c b/app/src/input_manager.c
index fb8ef8f..89cb4ae 100644
--- a/app/src/input_manager.c
+++ b/app/src/input_manager.c
@@ -402,7 +402,8 @@ input_manager_process_mouse_button(struct input_manager *input_manager,
                                    const SDL_MouseButtonEvent *event,
                                    bool control) {
     if (event->type == SDL_MOUSEBUTTONDOWN) {
-        if (control && event->button == SDL_BUTTON_RIGHT) {
+        if (control && (event->button == SDL_BUTTON_RIGHT ||
+                        event->button == SDL_BUTTON_X1)) {
             press_back_or_turn_screen_on(input_manager->controller);
             return;
         }
```

Could you confirm, please? (I have no mouse with button 4)
