### ISSUE TITLE
LAGGY AS HELL ANDROID 13

### ISSUE THREAD

**Issue by ClientBeta** [Genymobile/scrcpy#4365]
- [x] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [x] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: [Windows 11 home]
 - scrcpy version: [2.1.1]
 - installation method: [Windows release...]
 - device model: 2201117TG(Redmi note 11)
 - Android version: [13]

**Describe the bug**
framedrop MIUI 14.0.2 unexpected no forge or background apps was open in the phone nor PC
i tried manually lowering the resolution and the frames dosnt work

**Comment by rom1v** [comment]
If you record (`scrcpy --record=file.mp4`), is the recorded file laggy?

Is your physical screen broken?

**Comment by slai47** [comment]
I'm also having this issue via win64-v2.0 but with Android 14.

OS: Windows 10 Pro (10.0.19045)
scrcpy 2.0
installation: Windows Release
Device: Asus Rog Phone 5S 
Android Version: 14

I run this command to stream my screen to my computer and record game play. The lag only happens when I have the recording appended.

`cmd /c scrcpy.exe --lock-video-orientation=1 --window-width 2000 --stay-awake --record=C:\Users\slai4\Videos\GameplayOnly.mp4`

The video on the screen gets slow and sluggish but the recording and my phone is smooth as butter.

**Comment by rom1v** [comment]
> scrcpy 2.0

> The lag only happens when I have the recording appended.

Could you reproduce with scrcpy 2.1.1? (refs 9d3c656414ac096ae30e42c22671c72a6bd491af).

**Comment by slai47** [comment]
I just updated post that stream. I'll test it out and let you know

**Comment by slai47** [comment]
Updated and I think I know the issue for me. I believe the fps issues between my phone at 144hz to scrspy caused the issue. Switching my phone to 60fps makes it way smoother.

**Comment by rom1v** [comment]
Or use `scrcpy --max-fps=60`?

**Comment by slai47** [comment]
@rom1v you are correct. That fixed it as well. Thank you!
