### ISSUE TITLE
V2.3.1 install_release.sh calls for wrong scrcpy-server version

### ISSUE THREAD

**Issue by nate2014jatc** [Genymobile/scrcpy#4617]
- [ X ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ X ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).

**Environment**
 - OS: Linux Mint
 - scrcpy version: 2.3.1
 - installation method: Manual Build
 - device model: Nothing Phone (1)
 - Android version: 13

**Describe the bug**
Build script calls for incorrect version of pre-built server, leading to client application refusing to start citing that the server and client have a version mismatch. 

Prebuilt server URL reads `releases/download/v2.3/scrcpy-server-v2.3` 
instead of `releases/download/v2.3.1/scrcpy-server-v2.3.1`

Changing this manually leads to a successful build and run.

**Comment by rom1v** [comment]
Please read explanation in https://github.com/Genymobile/scrcpy/issues/4098.

You should not execute ./install_release.sh from tag v2.0, but one commit after (in practice, it is intended to be called from current master only).

**Comment by nate2014jatc** [comment]
That is a very peculiar workflow. I would normally expect the contents of the source archive of a release tag to be able to build that release tag.

I normally build from release tags as the current master (in other projects) tends to be volatile.

**Comment by rom1v** [comment]
> I would normally expect the contents of the source archive of a release tag to be able to build that release tag.

That's the case: you can build the full release with `./release.sh` from the tag.

`./install_release.sh` is a bit peculiar indeed, it has just been added to simplify the installation with a prebuilt server (instead of following the instructions manually from a documentation file). It is intended to build the latest release on master. I did not want to put it in a separate repo for convenience, but it is not intended to be executed from release tags (for the reasons explained in the linked comment).

**Comment by rom1v** [comment]
Btw, you can't take any random commit and execute `./install_release.sh` either, because the prebuilt server is published for each release only, not for every commit, so the client and the server may be incompatible.
