### ISSUE TITLE
Simultaneously control of several device from one window.

### ISSUE THREAD

**Issue by mrGoncharuk** [Genymobile/scrcpy#471]
Hi there! I have 100 identical android devices and i need to configure all of them(remove useless apps, logging into google work accounts, add to folder google work apps...).What do you think about controling several devices from one scrcpy window. Every action from window repeats on each device. Actions are similar beacause devices are enw and similar.

In another way, may be it would be easier to read and save actions(input) from android device/scrcpy prog and then send perform this actions in other devices.

I will be glad to hear back from you.
You can get in touch with me by telegram: @zielony_rolnik or by email: catmanboy1@gmail.com
P.S I don't know where discussion is so i decide to write here

**Comment by rom1v** [comment]
Hi,

For information, _scrcpy_ has been initially developed as a feature of a Genymobile product called [Genydeploy](https://www.genymotion.com/genydeploy/), which does what you say (and which uses controls more reliable than input events for automation). You could contact them if you are interested.

> What do you think about controling several devices from one scrcpy window.

This would only work if the device have the same resolution, and it would require to select which one to show… I think it would add too much complexity for scrcpy, for something it is not made for.

> In another way, may be it would be easier to read and save actions(input) from android device/scrcpy prog and then send perform this actions in other devices.

That would be less intrusive, so why not.

But for this purpose, I think replaying lower-level events with [AOA](https://source.android.com/devices/accessories/protocol) is more appropriate, since it can control devices even with adb disabled (see https://github.com/Genymobile/scrcpy/issues/279#issuecomment-453819354). (For info, _Genydeploy_ has such a feature.)

**Comment by mrGoncharuk** [comment]
Thank you for yours reply! I tried to google how to solve my problem but found nothing. I thoght that such software does not exist but with yours help i got to know that it is :)
Thank you again! I find out everything what i need. Good luck 🥇

**Comment by diduweiwu** [comment]
> Thank you for yours reply! I tried to google how to solve my problem but found nothing. I thoght that such software does not exist but with yours help i got to know that it is :)
> Thank you again! I find out everything what i need. Good luck 🥇

Hi there, QtScrcpy or SoloPi may help something for your requirement.

**Comment by ji4ozhu** [comment]
What you might need is he www.911tp.com is also based on scrcpy development
