### ISSUE TITLE
Custom delay to avoid frame drops

### ISSUE THREAD

**Issue by StylishBoyGaming** [Genymobile/scrcpy#472]
I want custom delay in scrcpy. Because when I play pubgm it's started frame drops in scrcpy window . In custom delay it can easiest way to rid of skipped frames

**Comment by rom1v** [comment]
Is this problem different from https://github.com/Genymobile/scrcpy/issues/466?

Why do you say that custom delay would help? How do you know that frames are skipped?

By default, _scrcpy_ always display the very last available frame to minimize lag. Frames are not buffered.

If you do not want to skip frames, there is a compilation flag that will not replace the frame to render if the previous one has not been rendered yet:

    meson configure x -Dskip_frames=false
    ninja -Cx

In practice, I think it's not very useful, because if frames are skipped because the computer is too slow, then waiting for the previous frame to be rendered will just add lag to the following frames (unless if it is just very temporary). In other words, if the computer is not fast enough to decode and render the video, there will be a problem anyway.

**Comment by StylishBoyGaming** [comment]
Can you give me  scrcpy.exe with this confurigation meson configure x -Dskip_frames=false
ninja -Cx

**Comment by StylishBoyGaming** [comment]
hey @rom1v ,does scrcpy needs good android phone for mirror ???

**Comment by rom1v** [comment]
> Can you give me scrcpy.exe with this confurigation

Oops, I answered in the other thread: https://github.com/Genymobile/scrcpy/issues/466#issuecomment-475942046

> does scrcpy needs good android phone for mirror ???

In general it works correctly. What's your device?

I'm not sure I understand exactly where you have a performance problem (device-side or computer-side).

**Comment by rom1v** [comment]
Also, did you try with SDL 2.0.8 as suggested [here](https://github.com/Genymobile/scrcpy/issues/466#issuecomment-475516659)?

**Comment by StylishBoyGaming** [comment]
yes its  works thanks bro sdl works for me...

**Comment by sanjeevo7** [comment]
How to add delay in Scrcpy? I use Scrcpy and Sndcpy both for video and audio, Scrcpy works Fine but there is 
problem in Sndcpy that is audio delay (approx 1sec). So I want to add delay in video to synchronise audio and video both. Hope anyone can help me!
