### ISSUE TITLE
Make 2 days of this thing pls help.. 

### ISSUE THREAD

**Issue by LouisPham91** [Genymobile/scrcpy#4814]
https://news.ycombinator.com/item?id=16546276
like what u said but however i did i cant find a solution
how bypass this bug
![image](https://github.com/Genymobile/scrcpy/assets/21294927/3504f386-6b5a-4b9f-9924-3b643e6b02a4)

**Comment by rom1v** [comment]
You already opened an issue for this question #4809.

There is a bug related to "adb reverse" for devices connected over TCP/IP on old versions of Android. There's nothing you could do about that, except upgrading your device.

But scrcpy does not need it (since #5 is fixed), because a fallback is implemented to use `adb forward` instead. So this is a non-problem for scrcpy. You will just get the incorrect error message `adb.exe: error: more than one device and emulator` produced by adb, but you can safely ignore it.
