### ISSUE TITLE
fraud possibility? 

### ISSUE THREAD

**Issue by khoftuk2** [Genymobile/scrcpy#4843]
suppose some on who borrowed my phone to make a call, gets the necessary info to start scrcpy and uses this app as a spy work.
how can I, the victim, can put a stop to that? 
please help, because I think I'm being spied on :(

**Comment by rom1v** [comment]
Once a malicious user has access to your physical device, he can enable USB debugging, plug your device and connect from his computer and validate the connection authorization. Once he has done that, he has a very privileged access to your device (scrcpy or not) when it is connected via USB or wifi on the same network.

If he just plans to use scrcpy, disabling USB debugging or revoking the USB debugging authorizations is sufficient. Even just not being connected to the same local network typically "prevents" to connect to your device via `adb connect`, so for example he could not use scrcpy to control your device while you're only connected via your mobile network.

Of course, if he had a physical access to your device, instead of scrcpy, he could possibly have installed some malicious spy application that could track you everywhere and send reports to a server he controls…

**Comment by khoftuk2** [comment]
> Once a malicious user has access to your physical device, he can enable USB debugging, plug your device and connect from his computer and validate the connection authorization. Once he has done that, he has a very privileged access to your device (scrcpy or not) when it is connected via USB or wifi on the same network.
> 
> If he just plans to use scrcpy, disabling USB debugging or revoking the USB debugging authorizations is sufficient. Even just not being connected to the same local network typically "prevents" to connect to your device via `adb connect`, so for example he could not use scrcpy to control your device while you're only connected via your mobile network.
> 
> Of course, if he had a physical access to your device, instead of scrcpy, he could possibly have installed some malicious spy application that could track you everywhere and send reports to a server he controls…

in this case, this is very possible, do you have any idea how to put a stop to that? or should i just put my android away?!
