### ISSUE TITLE
Virtual display keeps increasing.

### ISSUE THREAD

**Issue by ibnusaja** [Genymobile/scrcpy#5534]
When I run the program `scrcpy --new-display=1920x1080`, the new display works normally and outputs the log:  
`[server] INFO: New display: 1080x1080/384 (id=1)`  

However, when I close it and run it again, another log appears:  
`[server] INFO: New display: 1080x1080/384 (id=2)`.  

This keeps happening continuously. Even though I have closed the window of the display, the new display ID keeps increasing.  

As shown in the image below, many displays are detected when I run the command `dumpsys display`.  

*So, my question is:*
1. how can I reset the display IDs?  
2. And if possible, is there a way to return to the previous display session (resume session ID before) ?

### Thank you for creating this application that has been very helpful for my work. 
...... 
![Untitled](https://github.com/user-attachments/assets/8126f643-ea4c-4dff-bcc6-ae392b510ec0)

**Comment by rom1v** [comment]
The active displays (virtual or not) can be listed by `scrcpy --list-displays`.

In practice, it is expected that the id keep increasing (it's just a "unique" id).

> how can I reset the display IDs?

The id counter is reset on reboot.

> And if possible, is there a way to return to the previous display session (resume session ID before) ?

No, as soon as you close scrcpy, it is destroyed, due to this flag (IIRC):

https://github.com/Genymobile/scrcpy/blob/74aecc00b512969fa3b067ed3cf20e12194206d2/server/src/main/java/com/genymobile/scrcpy/video/NewDisplayCapture.java#L171

**Comment by ibnusaja** [comment]
Oh, thank you. I was thinking that the increasing number of unique display IDs might add more load to the CPU/RAM.

Thank you for your answer. Thank you.
