### ISSUE TITLE
Navigation gestures no longer work using a mouse in fullscreen apps

### ISSUE THREAD

**Issue by livingator** [Genymobile/scrcpy#5545]
## Environment

- OS: Windows 10
- Scrcpy version: 3.0
- Installation method: Windows release
- Device model: S22 Ultra
- Android version: Android 14

## Describe the bug

Can no longer use navigation gestures (back/home app switch) in fullscreen apps with immersion mode through mouse swiping since upgrading to Scrcpy 3.0 (it's still fine in 2.7).

**Comment by rom1v** [comment]
As I expected, the change is caused by d19396718ee0c0ba7fb578f595a6553c0458da59.

With this dirty hack (the position mapper is not updated), it "works":

```diff
diff --git server/src/main/java/com/genymobile/scrcpy/control/Controller.java server/src/main/java/com/genymobile/scrcpy/control/Controller.java
index f0e4c0374..e0533fff9 100644
--- server/src/main/java/com/genymobile/scrcpy/control/Controller.java
+++ server/src/main/java/com/genymobile/scrcpy/control/Controller.java
@@ -139,7 +139,7 @@ public class Controller implements AsyncProcessor, VirtualDisplayListener {
 
     @Override
     public void onNewVirtualDisplay(int virtualDisplayId, PositionMapper positionMapper) {
-        DisplayData data = new DisplayData(virtualDisplayId, positionMapper);
+        DisplayData data = new DisplayData(0, positionMapper); // hack
         DisplayData old = this.displayData.getAndSet(data);
         if (old == null) {
             // The very first time the Controller is notified of a new virtual display
```

But I think the correct way is to send mouse events to the (mirroring) virtual display, not the main display. I have no control over how Android reacts to these events though.

Side-note: you can press BACK using right-click and HOME using middle-click by default.

**Comment by rom1v** [comment]
Please test https://github.com/Genymobile/scrcpy/issues/5605#issuecomment-2518705189

**Comment by rom1v** [comment]
Please test #5614.

**Comment by livingator** [comment]
> Please test #5614.

tested and it works
