### ISSUE TITLE
what is the maximum bitrate?

### ISSUE THREAD

**Issue by almaceleste** [Genymobile/scrcpy#558]
what is the maximum bitrate for scrcpy?  
8 Mbps? or I can set better?

**Comment by rom1v** [comment]
The bitrate is just forwarded to the codec:

https://github.com/Genymobile/scrcpy/blob/a41dd6c79f542925c5db7f1ee51d27b65ba832ec/server/src/main/java/com/genymobile/scrcpy/ScreenEncoder.java#L142

How it is used is encoder-dependant. In practice, beyond 12 or 16, it does not change anything.

**Comment by almaceleste** [comment]
how can I know my encoder dependence?

**Comment by jbd11** [comment]
I want to know this too
I tried game mirroring, the bitrate drops a lot on pc screen
how can I see the mirrored screen exactly as good as (same as original bitrate) the original mobile screen?

**Comment by jbd11** [comment]
so how can I check the encoder for this scrcpy and upgrade it to display same bitrate as my mobile phone screen?

**Comment by jbd11** [comment]
downloaded and updated codec but still same no lag but bitrate drops so much

**Comment by rom1v** [comment]
> how can I see the mirrored screen exactly as good as (same as original bitrate) the original mobile screen?

The screen surface is not encoded to render on the device, so you can't have the same quality without any loss. The raw content for a 1920×1080 video at 60 fps would require 1920×1080×24×60 bits per second, which is 3Gbps.

So the content is encoded in H.264 with a live hardware encoder. Since it's in live, the quality cannot be as good as possible for a given bitrate.

The bitrate is passed as-is to MediaCodec, and the way it impacts the encoding is encoder-dependant (and the max value too).

**Comment by rom1v** [comment]
> the bitrate drops a lot on pc screen

Is the quality so bad?

Could you post a recording of several seconds?

    scrcpy --record file.mkv
