### ISSUE TITLE
Overheating, Gaming problem

### ISSUE THREAD

**Issue by tuevudeptrai** [Genymobile/scrcpy#5586]
LT and RT are now usable when I use LHLaurini Scrcpy, Tho I still have overheating issues can someone help me with it, and why do the LHLaurini able to use LT and RT tho the 3.0 version are not, I've try emulate a ps4 and the gamepad tester said it's a xbox 360, meant that LHlaurini version are emulated another controller so why can't do that on the 3.0 ver, and can you add another setting to change the encoder from phones to PC because it's getting overheating whenever I gaming

Mi 10
Android 13

Window 10

**Comment by rom1v** [comment]
> why do the LHLaurini able to use LT and RT tho the 3.0 version are not

The initial version from LHLaurini uses `uinput`, while scrcpy uses `uhid` (https://github.com/Genymobile/scrcpy/pull/2130#issuecomment-2276249226):

> The main difference is that it injects events in UHID format to `/dev/uhid`, while this PR injects events in the UINPUT format to `/dev/uinput`.
>
> The reason why it is problematic to use uinput is that it requires a call to ioctl(), which cannot be easily performed in Java, so it requires either a native dependency or to add native code, which I would like to avoid in scrcpy.

The gamepad in scrcpy is implemented by #5270:

> There was a PR (https://github.com/Genymobile/scrcpy/pull/2130) implementing gamepad support using uinput on the device. However, this required to add a native dependency or to add native code (cf https://github.com/Genymobile/scrcpy/pull/2130#issuecomment-2276249226).
>
> This PR uses HID instead, and provides support for AOA and UHID (like for keyboard and mouse).
It does not add any dependency, and it also works in OTG mode (via AOA), so even without USB debugging.

In addition, as I said in https://github.com/Genymobile/scrcpy/issues/5559#issuecomment-2506676819, the implementation in scrcpy by #5270 uses a generic controller, and it turns out that some games do not behave correctly with a generic controller.

To fix that, we would need to add a feature to simulate a well-known controller: https://github.com/Genymobile/scrcpy/issues/5362#issuecomment-2483497323

> Overheating

Running a game and encoding the screen consumes resources, depending on the device hardware it might heat.

You can reduce the resolution/bit rate, or try another encoder/codec (depending on your device): https://github.com/Genymobile/scrcpy/blob/master/doc/video.md

**Comment by tuevudeptrai** [comment]
but the LHLaurini version I can't change the encoder, how can I change it

**Comment by rom1v** [comment]
The version you use from LHLaurini was a fork from an old scrcpy version, so it's an old version without all the new features and fixes.

I didn't check, but it migbt be a version where `--video-encoder` was named `--encoder` (before audio forwarding was implemented).

**Comment by tuevudeptrai** [comment]
I was using scrcpy normally until today (still using scrcpy 3.1 or smth) the phone got overheating, first I thought It's because I tweak the hardware a little bit but then I try to turn off scrcpy it drop from 77 Celcius to 40 Celcius 
![image](https://github.com/user-attachments/assets/5fc008a1-c53f-42b2-bb35-26037bb0faf2)
mostly at 70 degrees sometime it'll jump to 77 and almost 80
![image](https://github.com/user-attachments/assets/b7f2292b-6bef-4cd8-a220-2e8dae9cb20c)
![image](https://github.com/user-attachments/assets/d480015f-bac6-431b-bc12-4e4661127383)

I only plug in for like a few sec and It just rapidly jump from 40 to 78

**Comment by tuevudeptrai** [comment]
This literally never happens before I've said before that it overheating but not like this, and my phone hardware is kinda good, it can handle genshin impact max setting at 60fps, I've reduce the resolution to 1366 too but it didn't work

**Comment by tuevudeptrai** [comment]
![image](https://github.com/user-attachments/assets/e1ac314d-a030-4c49-80f5-a75251b80caf)
idk what's wrong but when I tried to run scrcpy without turn of the screen it do not overheat, but idk why the fps are so low like it's only 10fps or smth

**Comment by tuevudeptrai** [comment]
![image](https://github.com/user-attachments/assets/5095121d-9a01-437c-bce7-d17b037ea78f)
it does get stuck at 11 fps

**Comment by rom1v** [comment]
See #3376.

**Comment by tuevudeptrai** [comment]
turn out everything are ok now after I use a replace a new screen on my phone, I've take it off and that's maybe the reason
