### ISSUE TITLE
CRITICAL: Could not lock mutex

### ISSUE THREAD

**Issue by shplack** [Genymobile/scrcpy#608]
Hey! Love the software! 
I've only had one teensy problem since I've started using scrcpy.

Using the arguments:
-S
-n
--render-expired-frames

at the same time causes a critical error "CRITICAL: Could not lock mutex"

If I remove any of the above arguments, it works fine, but it is impossible to use all three in tandem.

Thanks for making my life easy with this software!

**Comment by rom1v** [comment]
Thank you for your report.

I think it only occurs with `-S` and `-n` (not `--render-expired-frames`).

The problem is that `--no-control` means "do not control the device at all" (see acc4dcd520f960a3e5d8fb431ceb0cbc3e7825e4). So the controller is not even started (both on the client and the server).

For now, I fixed the crash bfb3f0842f523b315ec92668bb15818fb3883bab.

Maybe we need some mode "do not control the device except to power it on on start and turn screen off", but I'm not sure…
