### ISSUE TITLE
Encoder color format?

### ISSUE THREAD

**Issue by alexkiri** [Genymobile/scrcpy#638]
I noticed that colors, especially reds, look different in scrcpy.
screenshot from scrcpy output:
![Clipboard02](https://user-images.githubusercontent.com/6061770/60942597-dc62fd80-a2eb-11e9-86d3-4803cb663c3d.jpg)

screenshot from phone:
![Clipboard02b](https://user-images.githubusercontent.com/6061770/60942598-dc62fd80-a2eb-11e9-9323-86e671afe9cb.jpg)

crop:
![Clipboard03](https://user-images.githubusercontent.com/6061770/60942599-dc62fd80-a2eb-11e9-86f3-5bdc48d12c50.png)

I believe that the issue here is the color format. The encoder most likely uses yuv420.
I have tried to change this line:
`format.setInteger(MediaFormat.KEY_COLOR_FORMAT, MediaCodecInfo.CodecCapabilities.COLOR_FormatSurface);` 
to `COLOR_FormatYUV444Flexible`, but it doesn't work. I am getting:
>ERROR: Could not open video stream

Is there anything I can try? I have already setup my machine, and I can make my own build.

**Comment by rom1v** [comment]
Hi,

I opened this PR page in Firefox on an Android device, captured a screenshot with:

    adb exec-out screencap -p > cap.png

I opened it with `feh`. I also launched _scrcpy_, then take a capture from the computer using `xfce4-screenshooter`.

Here is the result I get:
![side-by-side](https://user-images.githubusercontent.com/543275/60957705-61a6dc00-a305-11e9-9b45-09b0b28dc115.png)

On large surfaces (like the red of the strawberry), the color is the same on the left and on the right.

The only difference is on the `CANCEL` and `DELETE` words. Since it only happens there, I think this is just an expected artefact of the lossy encoding process. This is either due to compression of high-frequencies ([DCT+quantization](http://www.dspguide.com/ch27/6.htm)) because the text is thin, or [chroma subsampling](https://en.wikipedia.org/wiki/Chroma_subsampling). As you suggested, disabling chroma subsampling (4:4:4 instead of 4:2:0) could have solved the problem for the text, but it seems `MediaCodec` cannot encode to a 4:4:4 output format.

Anyway, this is not the problem you observe between your two screenshots: the strawberry does not look the same in the top and bottom picture. I cannot reproduce this: I superimposed the two images on the bottom in different gimp layers, then enabled one or the other, there is no difference except on thin text (`CANCEL`, `DELETE`).

How did you screenshot on the device and on the computer?

**Comment by alexkiri** [comment]
Thanks for you quick reply, and also for you work on this excellent work on this application.

I have taken the device screenshot using the system key combo Power+VolumeDown. On the computer, I have taken the screenshot with PrintScreen, after making _scrcpy_ fullscreen.

On a second thought, I now have doubts that the chroma subsampling is the issue. If it was, it should affect color resolution only. The color itself should not be affected, the hue / saturation should remain the same.

**Comment by rom1v** [comment]
> If it was, it should affect color resolution only. The color itself should not be affected, the hue / saturation should remain the same.

The thing is, the letters have lines less than 2 pixels wide (so less than 1 pixel in the chroma planes). As a consequence, it may contain a mix of the background and the foreground color.

**Comment by alexkiri** [comment]
Ok, so then it may affect the color then.

But, if you're saying that MediaCodec cannot encode to a 4:4:4 output format, then is there any solution for this issue?

**Comment by rom1v** [comment]
> then is there any solution for this issue?

For the letters, I don't know, but loss in quality is expected.

But in the image from your initial post, the strawberry has clearly a different red. This is a different problem (and I cannot reproduce it).

**Comment by alexkiri** [comment]
I have found the cause.
Huawei seems to apply a filter that enhances the saturation of everything. What `scrcpy` sees (and also `adb screenshot`, as you can see below is the frame before this filter gets applied. The phone screenshot function includes this post processing.
adb screenshot:
![screenshot_adb](https://user-images.githubusercontent.com/6061770/61063719-1c6bd280-a409-11e9-828e-bc89f5179cb7.png)
scrcpy printrscreen:
![screenshot_prtscr](https://user-images.githubusercontent.com/6061770/61063720-1c6bd280-a409-11e9-9c05-4fabbda78b12.png)
phone screenshot:
![screenshot_droid](https://user-images.githubusercontent.com/6061770/61063721-1d046900-a409-11e9-9132-a3723aa504a7.jpg)
