### ISSUE TITLE
Restart on short WiFi disconnects

### ISSUE THREAD

**Issue by Magicoo** [Genymobile/scrcpy#685]
Hello,
Is it possible to auto-restart scrcpy -c 1224:1440:0:0 -f instead of just:
`WARN: Cannot terminate server
Press any key to continue...`
This happens to me at random times (sometimes minutes, sometimes hours) and it would be great to restart scrpy instead of opening a new cmd window and typing the scrcpy -c 1224:1440:0:0 -f again.
Thank you!

**Comment by Magicoo** [comment]
A workaround would be to make scrcpy exit by itself instead of asking to press a key. Any hint on how to do that please?

**Comment by rom1v** [comment]
The message:
> Press any key to continue...
is printed on Windows if "noconsole" is disabled when an error occurs: https://github.com/Genymobile/scrcpy/commit/140b1ef6a5f2de489f99c6f7f63dc2a49bc404f6

The purpose is to let the user see error messages.

I don't have a Windows right now to test, but maybe you could do something `scrcpy-noconsole.exe` (I don't remember what happens if you run it from a `cmd` terminal).

**Comment by Magicoo** [comment]
Thank you! Noconsole works for me.

**Comment by shodanx2** [comment]
This solution might work for you
https://github.com/Genymobile/scrcpy/issues/721#issuecomment-2143601259
