### ISSUE TITLE
Capture Real-time Video Frames  

### ISSUE THREAD

**Issue by benchat** [Genymobile/scrcpy#711]
Nice Work!
I would like to capture and consume/manipulate the video streams/frames during the capture and display of the android device on my Windows PC. How can I achieve this using scrcpy.exe?

**Comment by rom1v** [comment]
Currently, scrcpy is a standalone app (not a lib), so it does not expose an easy way to retrieve the frames programmatically.

Since it's open source, you can just fork and edit to do what we want on new frame:

https://github.com/Genymobile/scrcpy/blob/8507fea2718141075de519a3f1f53c99951cd368/app/src/scrcpy.c#L134

Or you could also just use the scrcpy server and reproduce the steps the clients does (but the protocol is "internal" and changes across scrcpy versions). See #129, #613 and #673.

**Comment by benchat** [comment]
I'm not a pro in c ,  hence the reason as to why I asked. Kindly give me some more directions, or you could as well just add that part only. You're in the best position to assist. If only you could provide a way to at least access those frames externally, that could really help.

**Comment by benchat** [comment]
This https://github.com/Allong12/py-scrcpy sorted me out.
