### ISSUE TITLE
Further latency optimizations [ideas]

### ISSUE THREAD

**Issue by DanielMazurkiewicz** [Genymobile/scrcpy#719]
Guys,

Since you're able to crop image, are you able to technically and efficiently crop multiple images from one screen? And if so, wouldn't it help with reducing latency?

If process of screen casting from Android looks now like that:
1. Rendering frame
2. Encoding frame
3. Sending/Receiving
4. Decoding frame
5. Rendering decoded frame

And in such a scenario only one step can happen at the time.

Then splitting frame for example into two separate halfs should reduce overall latency because some of the above steps can be shifted and paralleled (rather in terms of resources than computational power, but possibly computational power too):
1. Rendering frame
2. Encoding 1/2 frame
3. Sending/Receiving 1/2 frame | Encoding 2/2 frame
4. Decoding 1/2 frame | Sending/Receiving 2/2 frame
5. Rendering 1/2 frame | Decoding 2/2 frame
6. Rendering 2/2 frame

So as you see when first half of the image is already encoded you can start sending it earlier  and simultaneously you can start to encode second half of the image. Not sure how size of image impacts on encoding time, but there is a chance also to benefit from faster encoding times when encoding smaller crops of image.

**Comment by rom1v** [comment]
Hi,

What you suggest is a kind of "hacky" tile encoding, managed externally (not by the encoder itself).

_(I recently implemented [tile encoding in rav1e](https://blog.rom1v.com/2019/04/implementing-tile-encoding-in-rav1e/), the AV1 encoder from Mozilla/Xiph.)_

> are you able to technically and efficiently crop multiple images from one screen?

I don't think so (not more efficiently than capturing the whole screen at once).

Since it's not managed by the codec, this also means you need 2 separate H.264 streams (interlaced or on 2 separate sockets).

It is also probably quicker to encode/decode the whole image at once than encoding two half-frames. And I think there is no benefit in rendering two-half frames separately.

Moreover, you'll get artifacts at "tiles" boundaries, since there won't be any deblocking/restoration across tiles.

So intuitively, this will not work better and add problems (and a lot of complexity). But the idea to parallelize to improve latency is good :wink:

**Comment by aiamuzz** [comment]
@rom1v ... may by off topic ... would it make sense to add gif file support ... it may not have real world demand(as mkv and mp4 pretty much fulfill it) but it sure will be easy to share and post gif video's here on github issue threads for trouble shooting etc ...

**Comment by DanielMazurkiewicz** [comment]
@rom1v

> (I recently implemented tile encoding in rav1e, the AV1 encoder from Mozilla/Xiph.)

That is cool! :-) I envy you, wish I had a time to put my hands on stuff like this :-)

> I don't think so (not more efficiently than capturing the whole screen at once).

Unfortunately I'm not familiar at all with implementation details nor API of that capturing and passing data to video encoder, I can only tell theoretically that if tiles would be bounded to full lines of image (thus representing continuous areas of memory), then performance impact should be rather close to nothing in terms of capturing partials of screen. Possibly encoding too (but that depends very much on hardware and API).

> Since it's not managed by the codec, this also means you need 2 separate H.264 streams (interlaced or on 2 separate sockets).

As for hardware encoders/decoders I know that switching contexts might be (but doesn't have to) expensive (or in some cases even impossible). But have no clue about how it works at Android/ARM platform.

> Moreover, you'll get artifacts at "tiles" boundaries, since there won't be any deblocking/restoration across tiles.

That will be an issue, wouldn't slight overlapping of tiles be a solution here (another hack ;-) )?

> So intuitively, this will not work better and add problems (and a lot of complexity).

Measurements - this is the only thing I *almost* fully trust ;-) (and "everything should be as simple as possible, but not simpler" ;-) )

**Comment by rom1v** [comment]
> That is cool! :-) I envy you, wish I had a time to put my hands on stuff like this :-)

Yes, implementing tile encoding was a very cool project, where I learnt a lot :smile:
