### ISSUE TITLE
how to Disable Right Click to exit 

### ISSUE THREAD

**Issue by WANASX** [Genymobile/scrcpy#732]
hello ! 
how to Disable Right Click to exit i need to use right click without  close anything

**Comment by rom1v** [comment]
On Android, right click is rarely used. Typically, you get contect menu with long left-click.

That's why in scrcpy right-click is mapped to BACK.

Why do you need right-click?

**Comment by WANASX** [comment]
can i remapped   right-click?  
i use keyboard mapper app to play pubg mobile in scrcpy   but in app  i need to use  right-click  to unlock mouse  
in app i cant change  map  right-click   

So i need to change mappedin scrcpy from back to nothing   
and thank you

**Comment by rom1v** [comment]
> can i remapped right-click?

No, you can't without modifying the source code.

**Comment by WANASX** [comment]
how i can get  source code to  modifying ? or  i need devloper ?

**Comment by WANASX** [comment]
@rom1v  please i need I need a solution

**Comment by rom1v** [comment]
Basically, let right-click being forwarded to the device:

```diff
diff --git a/app/src/input_manager.c b/app/src/input_manager.c
index 5258bed..58a1325 100644
--- a/app/src/input_manager.c
+++ b/app/src/input_manager.c
@@ -409,10 +409,6 @@ input_manager_process_mouse_button(struct input_manager *input_manager,
                                    const SDL_MouseButtonEvent *event,
                                    bool control) {
     if (event->type == SDL_MOUSEBUTTONDOWN) {
-        if (control && event->button == SDL_BUTTON_RIGHT) {
-            press_back_or_turn_screen_on(input_manager->controller);
-            return;
-        }
         if (control && event->button == SDL_BUTTON_MIDDLE) {
             action_home(input_manager->controller, ACTION_DOWN | ACTION_UP);
             return;
```

But in practice, it seems to do the same action as left click in many apps.

**Comment by WANASX** [comment]
Can you tell me what tools should I use to get here?

**Comment by WANASX** [comment]
I have download  scrcpy-master and edit in input_manager.c  and change  BUTTON RIGHT  event to this 
`input_manager_process_mouse_button(struct input_manager *input_manager,
                                    const SDL_MouseButtonEvent *event,
                                    bool control) {
     if (event->type == SDL_MOUSEBUTTONDOWN) {
-        if (control && event->button == SDL_BUTTON_RIGHT) {
-            press_back_or_turn_screen_on(input_manager->controller);
-            return;
-        }
         if (control && event->button == SDL_BUTTON_MIDDLE) {
             action_home(input_manager->controller, ACTION_DOWN | ACTION_UP);
             return;`


but now i dont now how to run it with scrcpy    can you help me

**Comment by rom1v** [comment]
>  and change BUTTON RIGHT event to this

(the `-` means you need to remove the lines)

> but now i dont now how to run it with scrcpy can you help me

Follow [BUILD](https://github.com/Genymobile/scrcpy/blob/master/BUILD.md).

**Comment by WANASX** [comment]
yes i remove  - 
  man i try Follow BUILD.  But I didn't know anything  its hard steps I did not understand how to do it

**Comment by WANASX** [comment]
If you find a link to explain from YouTube please help me

**Comment by WANASX** [comment]
i use windows 10

**Comment by rom1v** [comment]
Ref #1302

**Comment by richaardvark** [comment]
I wish there was some way to disable the right-click and scroll-wheel-click always going back and closing whatever I'm working on.  It drives me CRAZY and makes scrcpy almost unusable for me.  I guess I have an overly sensitive mouse but I constantly bump the middle mouse scroll-wheel button and then whatever I'm in the middle of doing instantly vanishes or is closed, sometimes to detrimental effect, with my losing data/information/work.  I can't believe there's not a simple override for this feature :(

**Comment by rom1v** [comment]
https://github.com/Genymobile/scrcpy#right-click-and-middle-click

**Comment by cewatkins** [comment]
Well, I totally agree, right click is regular shot in the head, I hadn't
bothered to look for a workaround.  And as far as mousing, because I
roasted my 5th screen so I'm using scrcpy or I can't do anything, the
scrolling and clicking, get's far more a chore than a finger...
But, I stay away from the droid interface if I can help it, it reminds me
of lunchbox mac's, except it's 500 islands direction like unix binary
compatibility was...  And the silly vendors  packing on their extra's some
of which is nearly impossible to use in the mouse situation..
Having done OTG, I can't remember, but I think the right button was doom
that way too.

**Comment by pawn343** [comment]
> hello ! how to Disable Right Click to exit i need to use right click without close anything

Try to look at the [mouse bindings documentation](https://github.com/Genymobile/scrcpy/blob/master/doc/mouse.md#mouse-bindings).
Insight:
`In AOA and UHID mouse modes, the default bindings are reversed: all clicks are forwarded by default, and pressing Shift gives access to the shortcuts (since the cursor is handled on the device side, it makes more sense to forward all mouse buttons by default in these modes).`
So, you can use `Shift`+`Right-click` to use the normal mouse right click.
And that also can be costomized by passing it as argument when executing the scrcpy command: `--mouse-bind=xxxx:xxxx`.

For the bonus, you can customize the `alt` button to it's functionality rather than just as modifier: `--shortcut-mod=ralt`.
Will use the right `alt` as modifier instead of the left one.

**Comment by ursmeili** [comment]
use ` --mouse-bind=----` to disable right-click (and all other mouse clicks apart from left-click)

**Comment by chr15m** [comment]
Anybody who came here playing Minecraft and you can't shift-crouch+right-click without it exiting to the main menu, here's the magic incantation:

`scrcpy --mouse=aoa --mouse-bind=++++`

This will pass both right-click and shift-right-click through so you can crouch and use things at the same time.

**Comment by rom1v** [comment]
> `scrcpy --mouse=aoa --mouse-bind=++++`

I suggest UHID instead (it works over adb, not via raw USB, so it avoids detection issues, and it also works over wifi):

```bash
scrcpy --mouse=uhid --mouse-bind=++++
# equivalent
scrcpy -M --mouse-bind=++++
```
