### ISSUE TITLE
Can't target specific ADB device

### ISSUE THREAD

**Issue by bitfabrikken** [Genymobile/scrcpy#86]
I have many devices connected, all showing with no issues with 'adb devices'
But there's no way to run scrcpy for one of those specific devices.
Is it possible or maybe a planned feature?

**Comment by rom1v** [comment]
scrcpy -s serial

**Comment by Grimthorr** [comment]
For me, running `scrcpy` with no arguments will end immediately with no output while I have multiple devices connected, unless I specify a device using `scrcpy -s serial`. Is this expected behaviour?

Is there a plan to introduce a UI to prompt users to select a device from the available devices?

Somewhat related: I notice that `scrcpy` [waits for the first frame to be received from the device before showing the UI](https://github.com/Genymobile/scrcpy/blob/821ec9843c32410b5088ee86ada70e61db23e119/app/src/scrcpy.c#L73). Would it be beneficial to show a "loading" screen while waiting for the device to respond?

I'm assuming these both depend on the intended use of `scrcpy` and whether it's technically considered a command rather than a GUI application?

**Comment by rom1v** [comment]
> For me, running scrcpy with no arguments will end immediately with no output while I have multiple devices connected […] Is this expected behaviour?

The "no output" part is not expected, but on Windows, [output does not work](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md#on-windows-i-have-no-output-in-the-console).

> Is there a plan to introduce a UI to prompt users to select a device from the available devices?

No.

> Would it be beneficial to show a "loading" screen while waiting for the device to respond?

It might be. It's not a priority though, since in practice, the loading/error messages are printed on _stdout_ (yeah, not for Windows, but it's a bug).

> I'm assuming these both depend on the intended use of scrcpy and whether it's technically considered a command rather than a GUI application?

Yes, it's a cli application. A wrapper GUI could be written (as another application, like `scrcpy-gui`), which would be responsible to select device and other stuff, and start `scrcpy` with the right arguments.

**Comment by Grimthorr** [comment]
> The "no output" part is not expected, but on Windows, output does not work.

Ah, this explains my issue.

> > Would it be beneficial to show a "loading" screen while waiting for the device to respond?
> 
> It might be. It's not a priority though, since in practice, the loading/error messages are printed on stdout/stderr (yeah, not for Windows, but it's a bug).
> 
> Yes, it's a cli application. A wrapper GUI could be written (as another application, like scrcpy-gui), which would be responsible to select device and other stuff, and start scrcpy with the right arguments.

This all makes sense, thanks for the swift reply & developing a great tool!

**Comment by bitfabrikken** [comment]
Thank! -s did the trick.
