### ISSUE TITLE
Can't screening with display off on Android 10

### ISSUE THREAD

**Issue by Gnonymous7** [Genymobile/scrcpy#878]
Yeah if i put -S on the startup, i cant control the phone with mouse and keyboard.
Also if i start without -S but using ctrl+o. Still freezing after.
Here is the error displayed on cmd:

[server] ERROR: Exception on thread Thread[Thread-1,5,main]
java.lang.AssertionError: java.lang.NoSuchMethodException: android.view.SurfaceControl.getBuiltInDisplay [int]
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getBuiltInDisplay(SurfaceControl.java:82)
        at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:164)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:113)
        at com.genymobile.scrcpy.Controller.control(Controller.java:73)
        at com.genymobile.scrcpy.Server$1.run(Server.java:45)
        at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NoSuchMethodException: android.view.SurfaceControl.getBuiltInDisplay [int]
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getMethod(Class.java:1693)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getBuiltInDisplay(SurfaceControl.java:80)
        ... 5 more

**Comment by rom1v** [comment]
Even with v1.10?

**Comment by Seumi** [comment]
> Even with v1.10?
> 
> There are two separate issues with this. One is fixed in v1.10 (#586, #587), the other (#835) is fixed on `dev` branch.

**i also get this problem with my oneplus7pro(android 10, scrcpy v1.10)**

PS C:\Windows\System32> scrcpy -S                                                                                       INFO: scrcpy 1.10 <https://github.com/Genymobile/scrcpy>                                                                D:\scrcpy\scrcpy-server.jar: 1 file pushed. 0.1 MB/s (22546 bytes in 0.159s)                                            INFO: Initial texture: 1440x3120                                                                                        [server] ERROR: Exception on thread Thread[Thread-1,5,main]                                                             java.lang.AssertionError: java.lang.reflect.InvocationTargetException                                                           at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplayPowerMode(SurfaceControl.java:96)                            at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:165)                                                     at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:113)                                                    at com.genymobile.scrcpy.Controller.control(Controller.java:73)                                                         at com.genymobile.scrcpy.Server$1.run(Server.java:45)                                                                   at java.lang.Thread.run(Thread.java:919)                                                                        Caused by: java.lang.reflect.InvocationTargetException                                                                          at java.lang.reflect.Method.invoke(Native Method)                                                                       at com.genymobile.scrcpy.wrappers.SurfaceControl.setDisplayPowerMode(SurfaceControl.java:94)                            ... 5 more                                                                                                      Caused by: java.lang.IllegalArgumentException: displayToken must not be null                                                    at android.view.SurfaceControl.setDisplayPowerMode(SurfaceControl.java:1523)                                            ... 7 more

**Comment by Gnonymous7** [comment]
> Even with v1.10?
> 
> There are two separate issues with this. One is fixed in v1.10 (#586, #587), the other (#835) is fixed on `dev` branch.

Just updated my scrcpy, now its working thanks

**Comment by naytonsan** [comment]
Hi, someone could be help me?
the "scrcpy -S" command does not work.
I am using **Windows 10** with **Samsung S9** with **android 10**.

**error**
`C:\Users\Nayton User\Documents\scrcpy-win64>scrcpy -S
C:\Users\Nayton User\Documents\scrcpy-win64\scrcpy-server.jar: 1 file pushed. 0.4 MB/s (22470 bytes in 0.059s)
INFO: Initial texture: 1440x2960
[server] ERROR: Exception on thread Thread[Thread-1,5,main]
java.lang.AssertionError: java.lang.NoSuchMethodException: android.view.SurfaceControl.getBuiltInDisplay [int]
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getBuiltInDisplay(SurfaceControl.java:82)
        at com.genymobile.scrcpy.Device.setScreenPowerMode(Device.java:164)
        at com.genymobile.scrcpy.Controller.handleEvent(Controller.java:113)
        at com.genymobile.scrcpy.Controller.control(Controller.java:73)
        at com.genymobile.scrcpy.Server$1.run(Server.java:45)
        at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.NoSuchMethodException: android.view.SurfaceControl.getBuiltInDisplay [int]
        at java.lang.Class.getMethod(Class.java:2072)
        at java.lang.Class.getMethod(Class.java:1693)
        at com.genymobile.scrcpy.wrappers.SurfaceControl.getBuiltInDisplay(SurfaceControl.java:80)
        ... 5 more
`

**Comment by rom1v** [comment]
Which scrcpy version?

**Comment by naytonsan** [comment]
`C:\Users\Nayton User\Documents\scrcpy-win64>scrcpy --version
scrcpy 1.9

dependencies:
 - SDL 2.0.8
 - libavcodec 58.35.100
 - libavformat 58.20.100
 - libavutil 56.22.100`

**Comment by rom1v** [comment]
So just use the latest version…

**Comment by naytonsan** [comment]
> So just use the latest version…

how can i do this on windows?

**Comment by naytonsan** [comment]
Hi, I install [scrcpy-win64-v1.12.1.zip](https://github.com/Genymobile/scrcpy/releases/download/v1.12.1/scrcpy-win64-v1.12.1.zip)

and it work, tks

**Comment by ShiverZm** [comment]
hello,i met the similar promble, my HUAWEI phone cannot screen on with display on,and sometime  screen off with display on need to try twice,there are some method to solve it ?

**Comment by rom1v** [comment]
@ShiverZm Sorry, I didn't understand. Why version btw?

**Comment by ShiverZm** [comment]
i met two problem, first problem:my HUAWEI phone cannot be lighted when i made it display on with screen off; the second,is that,i made it screen off with display on, i need try it twice,cirl+o twice,my HUAWEI is Android 10

**Comment by ShiverZm** [comment]
in addition,the cannot-not-light means my screen still off

**Comment by rom1v** [comment]
> first problem:my HUAWEI phone cannot be lighted when i made it display on with screen off;

Even with physical power button?

> i need try it twice,cirl+o twice

That's probably device-related.

Which version of scrcpy.
