### ISSUE TITLE
Pixel2 XL crashes on every PC / Mac

### ISSUE THREAD

**Issue by Entropiks** [Genymobile/scrcpy#916]
I've been trying to figure this issue out since I found scrcpy a few months back. It almost always run but at random it will simple close without any errors - Almost as if a user closed the window. I am getting the same exactly issue on a 2011 macbook pro with Yosemite, 2017 mac with Catalina, Surface Pro, my windows10 desktop all have the exact same issue happening. I have tried with multiple different USB-C cables as well. Thinking this may be a phone issue if constant across all computers?

Cheers

**Comment by rom1v** [comment]
> It almost always run but at random it will simple close without any errors - Almost as if a user closed the window.

This happens when the connection between the device and the computer ends.

To know if it comes from `adb`, run in a separate console `adb logcat`. If, when _scrcpy_ closes itself, `adb logcat` also terminates, then the device has been disconnected (from an _adb_ point of view).

This may also happen if USB is reconfigured (for example switches between MTP/PTP/etc).

Sometimes, it's the USB port/cable (#281 #283), but you already tested with several cables and several computers.

**Comment by Entropiks** [comment]
This is kind of what I was getting towards was that my ADB connection keeps failing / something keeps switching over on the device. Will run the logcat and report back.

**Comment by rom1v** [comment]
Maybe try with still another cable.

When it disconnects, does the vendorId:productId of your device changes? (as displayed by `lsusb` on linux, I don't know how to get this information easily on Windows)

Also, does it work without disconnecting over wifi?

**Comment by Entropiks** [comment]
Yes wifi works fine - have tried 4 cables. Have tried with that exact throughput on all devices with same error. Will report back regarding productid chaging.

**Comment by Entropiks** [comment]
Update ( Fixed ):

Using a usb hub on both PC as well as Mac OS Catalina has fixed the constant random disconnecting using the same cords that all didn't work with direct connection.
